### ISSUE TITLE
In the ARM architecture, "Jobs" reports an error - version 6.1.4

### ISSUE THREAD

**Issue by YyqBoy** [exceptionless/Exceptionless#696] opened 2020-08-31 08:55 UTC
The official advice “It is recommended to make index templates typeless by re-adding them with include_type_name set to false. Under the hood, typeless templates will use the dummy type _doc when creating indices.” 
PUT _template/template2?include_type_name=true

view the project  "Foundatio. Repositories. Elasticsearch", "Foundatio. Repositories" or even "Elasticsearch - net - 7.9.0" , there is no solution，Elasticsearch does not run in Docker; it is manually edited to RPM and then installed. God, help me.

Here is the error message:

System.ApplicationException: Error creating the index prod-events-v1-2020.08.28: Original: (400 - ElasticsearchClientException) Request failed to execute. Call: Status code 400 from: PUT /prod-events-v1-2020.08.28. ServerError: Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "**Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""
Server: (400) Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]**" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""

 ---> Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: PUT /prod-events-v1-2020.08.28. ServerError: Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""
   --- End of inner exception stack trace ---
   at Foundatio.Repositories.Elasticsearch.Configuration.Index.CreateIndexAsync(String name, Func`2 descriptor)
   at Foundatio.Repositories.Elasticsearch.Configuration.DailyIndex.EnsureDateIndexAsync(DateTime utcDate)
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.IndexDocumentsAsync(IReadOnlyCollection`1 documents, Boolean isCreateOperation, ICommandOptions options)
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.AddAsync(IEnumerable`1 documents, ICommandOptions options)
   at Exceptionless.Core.Pipeline.SaveEventAction.ProcessBatchAsync(ICollection`1 contexts) in /app/src/Exceptionless.Core/Pipeline/040_SaveEventAction.cs:line 23

**Comment by YyqBoy** [comment] 2020-08-31 10:41
It is generally understood that "exceptionless/elasticsearch:7.7.1" is to add some content, such as adding some analyzers. about elasticsearch, what should I pay attention to in order to use it with Exceptionless, under arm?

**Comment by niemyjski** [comment] 2020-08-31 13:34
This is a duplicate of #681, can you please see the discussion for the solution. Please let us know if you have any questions.

**Closed by niemyjski** 2020-08-31 13:34 UTC

**Comment by YyqBoy** [comment] 2020-09-01 07:08
Solved it, thanks
