### ISSUE TITLE
account suddenly disappeared

### ISSUE THREAD

**Issue by wuzhixing** [exceptionless/Exceptionless#691] opened 2020-08-24 00:54 UTC
I built exceptionless on my own server. I don't know why my account suddenly disappeared. When I log in, I am prompted that I can't find the user.

**Comment by niemyjski** [comment] 2020-08-24 13:15
How are you self hosting exceptionless? Are there still records in the elasticsearch user indexes?

**Comment by niemyjski** [comment] 2020-08-24 13:15
How are you self hosting exceptionless? Are there still records in the elasticsearch user indexes?

**Comment by wuzhixing** [comment] 2020-08-25 01:38
I use docker. I don't know what happened. When I went to work on Monday after the rest of Saturdays and Sundays, I found that the account was missing. At first, I thought that there was a problem with the service, so I restarted it. Later, I found that when I logged in, the interface returned that my account no longer exists

**Comment by niemyjski** [comment] 2020-08-25 19:25
That seems really odd. I'd use kibana and look to see if that record is still there for your user account.

**Comment by wuzhixing** [comment] 2020-08-26 06:43
I self hosting exceptionless.I can create the previous account. Under normal circumstances, if the existing account is not allowed to be created. But obviously I can create an account. It just means that my account is missing from the database. Including the apikey of the project. Because of the previous access to this apikey project, the log has been unable to upload.

**Comment by wuzhixing** [comment] 2020-08-26 06:45
![image](https://user-images.githubusercontent.com/40681332/91270115-ab4fc180-e767-11ea-9cd3-f19e82803c49.png)
when i login.

**Comment by wuzhixing** [comment] 2020-08-26 06:51
![image](https://user-images.githubusercontent.com/40681332/91270571-5d878900-e768-11ea-9b00-77caee035e52.png)
I have access to the exceptionless program. When I upload the log, it prompts that the apikey cannot be found

**Comment by wuzhixing** [comment] 2020-08-26 06:57
![image](https://user-images.githubusercontent.com/40681332/91271159-46956680-e769-11ea-8695-3c7db9492e25.png)
After seeing the log, I tried to register and found that the account registered before could be registered again. Then I found that the data was lost.

**Comment by wuzhixing** [comment] 2020-08-26 07:20
For those users who use self hosting, has no one ever fed back this problem?

**Comment by niemyjski** [comment] 2020-08-26 12:44
It sounds like your docker data or something was lost. This is not normal, what docker-compose file are you using? Are you using the one in our samples folder?

**Comment by wuzhixing** [comment] 2020-08-27 00:38
yeah.I used the one in your samples folder.I only updata ApiAddress and EX_EnableArchive.

**Comment by niemyjski** [comment] 2020-08-31 13:35
I'm really not sure then why data would go missing. Can you let us know if this happens again.

**Comment by wuzhixing** [comment] 2020-09-01 03:32
yeah！ It's happen again when i login in sunday.

**Comment by wuzhixing** [comment] 2020-09-01 03:34
![image](https://user-images.githubusercontent.com/40681332/91791910-dae94880-ec03-11ea-940e-ee4e86299f6c.png)
![image](https://user-images.githubusercontent.com/40681332/91791934-e6d50a80-ec03-11ea-8d7a-96273fa458e0.png)

**Comment by niemyjski** [comment] 2020-09-01 12:39
What does your indexes look like when you query them in elasticsearch (`GET _cat/indicies`)?

**Comment by wuzhixing** [comment] 2020-09-03 01:19
emmmmm. I don't know. My job is WPF. Therefore, I lack the knowledge of the back end. The reason why we first understand this exception is that it can record the WPF client log very well.

**Comment by niemyjski** [comment] 2020-09-03 12:11
I think this may be a duplicate of https://github.com/exceptionless/Exceptionless/issues/685. But that would never delete tokens. Is there anything in the application logs?

**Comment by liguob666** [comment] 2021-04-23 10:27
I also encountered the same problem. I encountered the same problem twice. The account disappeared by itself, but I can register again with the previous mailbox. It should be that the data in the database is gone. I don’t know where the data is stored, so I can’t verify the database. In the situation, is there an account like a super administrator that can manage all registered users from the interface? What could cause this problem?
#877
[https://github.com/exceptionless/Exceptionless/issues/877](url)

**Comment by niemyjski** [comment] 2021-04-23 13:00
Can you share your docker logs from your last successful run to when this happens? Are you pruning docker images/storage?

**Comment by liguob666** [comment] 2021-04-24 03:24
I am still learning docker and I don’t know how to find related logs and export logs

**Comment by liguob666** [comment] 2021-04-24 03:30
I ran it again using  docker-compose.all-in-one.yml  and applied it to my project. If something similar happens again a few days later, I can provide you with ubuntu login information. You can help me see what happened! thank!
@niemyjski

**Comment by niemyjski** [comment] 2021-09-01 02:33
@liguob666 I'm going to close this as it doesn't appear this is still happening. If it is can you please follow up.

**Closed by niemyjski** 2021-09-01 02:33 UTC
Labels: investigating
