### ISSUE TITLE
load fail Error with https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.15/lodash.min.js

### ISSUE THREAD

**Issue by XLJ-CN** [exceptionless/Exceptionless#678] opened 2020-07-25 08:56 UTC
hi sir, it's me
i use this in China , today i  get an error
![图片](https://user-images.githubusercontent.com/30283517/88453223-909fd980-ce97-11ea-9f8c-3ef96b3f2d62.png)
指向“https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.15/lodash.min.js”的 <script> 加载失败。
it means that load fail https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.15/lodash.min.js
how to deal with this problem. thank you

**Comment by niemyjski** [comment] 2020-07-28 12:13
Thanks for letting us know about this. This is a duplicate of https://github.com/exceptionless/Exceptionless.UI/issues/195 and has been implemented via a pr. Can you please follow this issue.

**Closed by niemyjski** 2020-07-28 12:13 UTC
