### ISSUE TITLE
" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]"

### ISSUE THREAD

**Issue by CoderRiker** [exceptionless/Exceptionless#955] opened 2021-08-19 06:40 UTC
![image](https://user-images.githubusercontent.com/88869889/130018770-c076d9d6-605d-4612-a904-a21b7090f6d7.png)

  **Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: PUT /prod-e
vents-v1-2021.08.19. ServerError: Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping d
efinition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root
 mapping definition has unsupported parameters:  [_size : {enabled=true}]""
   --- End of inner exception stack trace ---
   at Foundatio.Repositories.Elasticsearch.Configuration.Index.CreateIndexAsync(String name, Func`2 descriptor)
   at Foundatio.Repositories.Elasticsearch.Configuration.DailyIndex.EnsureDateIndexAsync(DateTime utcDate)
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.IndexDocumentsAsync(IReadOnlyCollection`1 documents,
Boolean isCreateOperation, ICommandOptions options)
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.AddAsync(IEnumerable`1 documents, ICommandOptions opt
ions)
   at Exceptionless.Core.Pipeline.SaveEventAction.ProcessBatchAsync(ICollection`1 contexts) in C:\Users\88548\Desktop\Ex
ceptionless\Exceptionless.API\src\Exceptionless.Core\Pipeline\040_SaveEventAction.cs:line 23**

When my client (using Nlog) submitted the log, I found that the data in es was not updated, so I started it with the console (originally using iis), and found that the put event could not be stored in es. I guess it was Foundatio.Repositories.AddAsync method does not support a certain grammar of es, because the ES version is 7.2.0 and no longer supports the creation of the specified type. The default type of the index is _doc. What are the official solutions?

**Comment by CoderRiker** [comment] 2021-08-19 06:54
UI.Verson:Exceptionless.UI-3.1.1
Api.Version:7.0.9
ElasticSearch.Version:7.10.0

**Comment by niemyjski** [comment] 2021-08-19 12:33
Thanks for reaching out to us. This is a duplicate of #681. You need to ensure the mapper-size plugin is enabled or disable it via configuration as shown in #681

Also please note that we don't officially support IIS hosting.

**Closed by niemyjski** 2021-08-19 12:33 UTC
