### ISSUE TITLE
could not be resolved : 'https://js.stripe.com/v2/'

### ISSUE THREAD

**Issue by zhouyongtao** [exceptionless/Exceptionless#317] opened 2017-08-29 13:31 UTC
sometimes can't open  https://js.stripe.com/v2/ domain in china . can fix load it in the project ?

**Comment by niemyjski** [comment] 2017-08-29 18:34
This is a duplicate of https://github.com/exceptionless/Exceptionless.UI/issues/150, we'd be more than happy to accept a pull request for this functionality.

**Closed by niemyjski** 2017-08-29 18:34 UTC
