### ISSUE TITLE
CDN problem reappears！Again and Again……

### ISSUE THREAD

**Issue by XLJ-CN** [exceptionless/Exceptionless#1096] opened 2022-05-17 01:38 UTC
sorry sir,CDN problem reappears !
I`m from China.
![image](https://user-images.githubusercontent.com/30283517/168708633-ae8e7214-1569-4d7d-8992-055182aaee00.png)

jsdelivr ! 
How can i do for it (my version is  7.0.9 and 7.2.1  ) thanks !

**Comment by XLJ-CN** [comment] 2022-05-17 06:22
Can use local js、css  files？

**Comment by niemyjski** [comment] 2022-05-17 11:16
Hello,

This is a duplicate of https://github.com/exceptionless/Exceptionless.UI/issues/195. We'd be more than happy to accept a pr for bringing in the dependencies but at this time we can't keep changing the cdn every year when a global acceptable cdn gets banned.

**Closed by niemyjski** 2022-05-17 11:16 UTC
