### ISSUE TITLE
Got an error when i published on ubuntu

### ISSUE THREAD

**Issue by xdqa01** [exceptionless/Exceptionless#833] opened 2021-02-03 07:33 UTC
Os:  Ubuntu 20.04 X64
nginx version: nginx/1.18.0 (Ubuntu)
exceptionless-api: label v709
I use nginx to proxy https://exceptionless-api.domain to http://localhost:4901 which is run by dotnet Exceptionless.Web.dll.
dotnet version:
```text
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /snap/dotnet-sdk/107/sdk/5.0.102/

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  5.0.102 [/snap/dotnet-sdk/107/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.2 [/snap/dotnet-sdk/107/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.2 [/snap/dotnet-sdk/107/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
error messgae:
```text
System.ApplicationException: Error creating the index prod-events-v1-2021.02.03: Original: (400 - ElasticsearchClientException) Request failed to execute. Call: Status code 400 from: PUT /prod-events-v1-2021.02.03. ServerError: Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""
Server: (400) Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""

 ---> Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: PUT /prod-events-v1-2021.02.03. ServerError: Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""
   --- End of inner exception stack trace ---
   at Foundatio.Repositories.Elasticsearch.Configuration.Index.CreateIndexAsync(String name, Func`2 descriptor)
   at Foundatio.Repositories.Elasticsearch.Configuration.DailyIndex.EnsureDateIndexAsync(DateTime utcDate)
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.IndexDocumentsAsync(IReadOnlyCollection`1 documents, Boolean isCreateOperation, ICommandOptions options)
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.AddAsync(IEnumerable`1 documents, ICommandOptions options)
   at Exceptionless.Core.Pipeline.SaveEventAction.ProcessBatchAsync(ICollection`1 contexts) in C:\workspaces\Exceptionless\src\Exceptionless.Core\Pipeline\040_SaveEventAction.cs:line 32
```

event content:
```text
[{"Id":"601a4d215025ca0b1e332743","OrganizationId":"601a3f68795b7a0dca0c8a0a","ProjectId":"601a3f68795b7a0dca0c8a0b","StackId":"601a4814895c5f0957dafc06","IsFirstOccurrence":false,"CreatedUtc":"2021-02-03T07:13:47.9388466Z","Idx":{"session-r":"601a4d215025ca0b1e332676"},"Type":"log","Source":"Microsoft.AspNetCore.Authorization.DefaultAuthorizationService","Date":"2021-02-03T15:13:37.961694+08:00","Tags":["Info"],"Message":"Authorization was successful.","Geo":null,"Value":null,"Count":null,"Data":{"@level":{"name":"Info","ordinal":2},"@version":"10.0.0","@environment":{"ProcessorCount":16,"TotalPhysicalMemory":0,"AvailablePhysicalMemory":0,"CommandLine":"*","ProcessName":"*","ProcessId":"28648","ProcessMemorySize":753233920,"ThreadName":null,"ThreadId":"25","Architecture":"X64","OSName":"Microsoft Windows 10","OSVersion":"10.0.18363","IpAddress":"27.38.37.66","MachineName":"*","InstallId":"34a0e55d380e4fb7b6576aa1fa62ad9e","RuntimeVersion":"5.0","Data":{"FrameworkDescription":".NET 5.0.2","ProcessArchitecture":"X64","ApplicationBasePath":"*","ApplicationName":"*","RuntimeFramework":".NETCoreApp,Version=v5.0"},"@user":{"Identity":"admin","Name":null,"Data":{}},"@request":{"UserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4385.0 Safari/537.36","HttpMethod":"GET","IsSecure":true,"Host":"localhost","Port":44302,"Path":"*","Referrer":"*","ClientIpAddress":"::1","Cookies":{"mongoMachineId":"7017974",".AspNetCore.Antiforgery.5VAU0jLELQ8":"CfDJ8KdZfGDaIP9JllR6Qhh2jFINlDc7ZPR0iLAaYpWzbfAPUrBeX6m0-hje_5NXBvQNDZ4VZjtgnb_k30rTGQeYJ5IZAoN-Wt0rF9rjDPD0BWAntB_IBhZ5YoC6k1ABxYIlgLawnRv8Me3fdkwWotH5_o8","idsrv.session":"1CD555F03F537123222A9CE9BDE33793","XSRF-TOKEN":"CfDJ8KdZfGDaIP9JllR6Qhh2jFJUcfAm9kj_aoaflbd3VTW1xCc2LSAQfa5WK7kuuWa-oZYKdFbjdvnUULvj-Bh7CeCBTQvBNdmJ0GSyAdNozxQI3rAo-0hPpySWbLk7PQ4yK-Ink62lJFphTx7OU4mRjBR9ivg5YJUWVUUc0wNzNUdxnUpJl5Kji9AI43z-uBRiQA",".AspNetCore.Identity.Application":"Value is too large to be included."},"PostData":null,"QueryString":{},"Data":{"@browser":"Chrome","@browser_version":"89.0.4385","@browser_major_version":"89","@os":"Windows","@os_version":"10","@os_major_version":"10","@is_bot":false}},"@submission_client":{"IpAddress":"27.38.37.66","UserAgent":"exceptionless","Version":"1.0.0.0"},"@ref:session":"601a4d215025ca0b1e332676"},"ReferenceId":"601a4d215025ca0b1e33269a"}}]
```

**Comment by xdqa01** [comment] 2021-02-03 07:38
`df -h`
`
Filesystem      Size  Used Avail Use% Mounted on
udev            1.9G     0  1.9G   0% /dev
tmpfs           394M  1.1M  393M   1% /run
/dev/vda1        40G  8.4G   29G  23% /
tmpfs           2.0G   12K  2.0G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/loop0       50M   50M     0 100% /snap/certbot/889
/dev/loop1       50M   50M     0 100% /snap/certbot/952
/dev/loop2       98M   98M     0 100% /snap/core/10583
/dev/loop3       56M   56M     0 100% /snap/core18/1944
/dev/loop5      129M  129M     0 100% /snap/dotnet-sdk/107
/dev/loop4       62M   62M     0 100% /snap/core20/904
tmpfs           394M     0  394M   0% /run/user/0
`

**Comment by xdqa01** [comment] 2021-02-03 07:44
appsettings.yml
`
---
Serilog:
  Using:
  - Serilog.Sinks.Console
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Warning
      Microsoft.Hosting.Lifetime: Information
      Microsoft.AspNetCore.Hosting.Diagnostics: Warning
      System: Warning
      Exceptionless.Web.Security.ApiKeyAuthenticationHandler: Warning
      Foundatio.Utility.ScheduledTimer: Warning
      Foundatio.Metrics: Warning
      #Exceptionless.Core.Repositories.EventRepository: Verbose
      #Exceptionless.Core.Repositories.StackRepository: Verbose
      #Exceptionless.Core.Repositories: Verbose
  WriteTo:
  - Name: Console
  Enrich:
  - FromLogContext
  - WithMachineName
  - WithThreadId

Storage: 'provider=folder;path=../storage'

# 'false' should config a redis
RunJobsInProcess: true

# Controls whether users can signup.
EnableAccountCreation: false

AuthOptions:
    EnableAccountCreation: false

Kestrel:
    Endpoints:
        Http:
            Url: "http://localhost:4901"
`

**Comment by niemyjski** [comment] 2021-02-03 12:50
Hello,

Thanks for reaching out to us. This is a duplicate of https://github.com/exceptionless/Exceptionless/issues/681. You need to ensure the mapper-size plugin is enabled or disable it via configuration as shown in #681

**Closed by niemyjski** 2021-02-03 12:50 UTC
