### ISSUE TITLE
ExceptionLess 6.1.3 ,  ES 7.8.1 ,what's wrong?

### ISSUE THREAD

**Issue by mine1202** [exceptionless/Exceptionless#689] opened 2020-08-19 14:37 UTC
[13:37:21 ERR] Error processing EventPost 4a79e42e01964a8d9e6c8e71736c8a1b archive/20/08/19/13/33/5f33a16d2a0d72001700e1ca/90e0ceff85a44ba78ad6f3a5b153822b.payload: Error creating the index prod-events-v1-2020.08.19: Original: (400 - ElasticsearchClientException) Request failed to execute. Call: Status code 400 from: PUT /prod-events-v1-2020.08.19. ServerError: Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""

Server: (400) Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""

System.ApplicationException: Error creating the index prod-events-v1-2020.08.19: Original: (400 - ElasticsearchClientException) Request failed to execute. Call: Status code 400 from: PUT /prod-events-v1-2020.08.19. ServerError: Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""

Server: (400) Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""

 ---> Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: PUT /prod-events-v1-2020.08.19. ServerError: Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""

   --- End of inner exception stack trace ---

   at Foundatio.Repositories.Elasticsearch.Configuration.Index.CreateIndexAsync(String name, Func`2 descriptor)

   at Foundatio.Repositories.Elasticsearch.Configuration.DailyIndex.EnsureDateIndexAsync(DateTime utcDate)

   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.IndexDocumentsAsync(IReadOnlyCollection`1 documents, Boolean isCreateOperation, ICommandOptions options)

   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.AddAsync(IEnumerable`1 documents, ICommandOptions options)

   at Exceptionless.Core.Pipeline.SaveEventAction.ProcessBatchAsync(ICollection`1 contexts) in /app/src/Exceptionless.Core/Pipeline/040_SaveEventAction.cs:line 23

baseURL add 
include_type_name=true  ?????

**Comment by mine1202** [comment] 2020-08-19 14:49
I use the ES installed by myself, and the version is 7.8.1

run by docker image of 6.1.3

The above error was reported when writing the log. Through Google search, some data mentioned that:

https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html


How to solve this problem?

**Comment by niemyjski** [comment] 2020-08-19 20:29
This is a duplicate of #681, can you please see the discussion for the solution. Please let us know if you have any questions.

**Closed by niemyjski** 2020-08-19 20:29 UTC
Labels: question

**Comment by mine1202** [comment] 2020-08-20 04:55
[400] POST /prod-events-2020.08.12%2Cprod-events-2020.08.13%2Cprod-events-2020.08.14%2Cprod-events-2020.08.15%2Cprod-events-2020.08.16%2Cprod-events-2020.08.17%2Cprod-events-2020.08.18%2Cprod-events-2020.08.19%2Cprod-events-2020.08.20/_search?typed_keys=true&ignore_unavailable=true



Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: POST /prod-events-2020.08.12%2Cprod-events-2020.08.13%2Cprod-events-2020.08.14%2Cprod-events-2020.08.15%2Cprod-events-2020.08.16%2Cprod-events-2020.08.17%2Cprod-events-2020.08.18%2Cprod-events-2020.08.19%2Cprod-events-2020.08.20/_search?typed_keys=true&ignore_unavailable=true. ServerError: Type: search_phase_execution_exception Reason: "all shards failed" CausedBy: "Type: illegal_argument_exception Reason: "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [data.@user.identity] in order to load field data by uninverting the inverted index. Note that this can use significant memory." CausedBy: "Type: illegal_argument_exception Reason: "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [data.@user.identity] in order to load field data by uninverting the inverted index. Note that this can use significant memory."""

[04:50:42 ERR] An error has occurred. Please check your search filter.

System.ApplicationException: Original: (400 - ElasticsearchClientException) Request failed to execute. Call: Status code 400 from: POST /prod-events-2020.08.12%2Cprod-events-2020.08.13%2Cprod-events-2020.08.14%2Cprod-events-2020.08.15%2Cprod-events-2020.08.16%2Cprod-events-2020.08.17%2Cprod-events-2020.08.18%2Cprod-events-2020.08.19%2Cprod-events-2020.08.20/_search?typed_keys=true&ignore_unavailable=true. ServerError: Type: search_phase_execution_exception Reason: "all shards failed" CausedBy: "Type: illegal_argument_exception Reason: "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [data.@user.identity] in order to load field data by uninverting the inverted index. Note that this can use significant memory." CausedBy: "Type: illegal_argument_exception Reason: "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [data.@user.identity] in order to load field data by uninverting the inverted index. Note that this can use significant memory."""

Server: (400) Type: search_phase_execution_exception Reason: "all shards failed" CausedBy: "Type: illegal_argument_exception Reason: "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [data.@user.identity] in order to load field data by uninverting the inverted index. Note that this can use significant memory." CausedBy: "Type: illegal_argument_exception Reason: "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [data.@user.identity] in order to load field data by uninverting the inverted index. Note that this can use significant memory."""



 ---> Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: POST /prod-events-2020.08.12%2Cprod-events-2020.08.13%2Cprod-events-2020.08.14%2Cprod-events-2020.08.15%2Cprod-events-2020.08.16%2Cprod-events-2020.08.17%2Cprod-events-2020.08.18%2Cprod-events-2020.08.19%2Cprod-events-2020.08.20/_search?typed_keys=true&ignore_unavailable=true. ServerError: Type: search_phase_execution_exception Reason: "all shards failed" CausedBy: "Type: illegal_argument_exception Reason: "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [data.@user.identity] in order to load field data by uninverting the inverted index. Note that this can use significant memory." CausedBy: "Type: illegal_argument_exception Reason: "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [data.@user.identity] in order to load field data by uninverting the inverted index. Note that this can use significant memory."""

   --- End of inner exception stack trace ---

   at Foundatio.Repositories.Elasticsearch.ElasticReadOnlyRepositoryBase`1.CountAsync(IRepositoryQuery query, ICommandOptions options)

   at Exceptionless.Web.Controllers.StackController.GetAllByTermsAsync(String aggregations, AppFilter sf, TimeInfo ti, String filter, String mode, Int32 page, Int32 limit) in /app/src/Exceptionless.Web/Controllers/StackController.cs:line 995

**Comment by mine1202** [comment] 2020-08-20 04:56
> This is a duplicate of #681, can you please see the discussion for the solution. Please let us know if you have any questions.
