### ISSUE TITLE
Docker Package ?

### ISSUE THREAD

**Issue by Nonobis** [exceptionless/Exceptionless#64] opened 2015-03-15 11:44 UTC
Hi,

With the release of the v2.0, maybe a docker package for self-hosted installation could be made ?
it could be really pratical to install a self-hosted installation with this...

i am thinking to remove my windows box where exceptionless server is installed and use a dedicaced synology nas for my git repo and exceptionless and webservice (with mono).

Could you tell me if this request could be possible ?

Pre-resquisites as docker image :

https://registry.hub.docker.com/_/mongo/
https://registry.hub.docker.com/_/elasticsearch/
https://registry.hub.docker.com/_/redis/
https://registry.hub.docker.com/u/library/mono/

thkx by advance for your response :)

**Comment by ejsmith** [comment] 2015-03-15 15:08
I love the idea and I want to get it to the point where it is that easy to host Exceptionless yourself, but I don't think the app will currently run on mono. I guess that is something that we need to try though since I don't think we are using anything that would cause it to not work.  Have you experimented with this at all?  If this is something that you are familiar with then maybe you can send us a pull request.

**Comment by Nonobis** [comment] 2015-03-15 17:54
sorry, i have got no experience with docker. i have discovered the system with the new dsm 5.2 (beta). There is other apps in .net who are working (sonaar) with docker. i will try to understand a docker file is working and maybe we could try it later. for mono, what's are the potential problem for you ?

**Comment by Nonobis** [comment] 2015-03-16 16:01
this seem to be possible, will try it if i got time this week... or in my holidays in may. :) 
http://friism.com/running-net-apps-on-docker

**Comment by niemyjski** [comment] 2015-03-16 19:13
+1, Please let me know what you find. I'm going to work very soon on making it really easy to self host.

**Comment by luisrudge** [comment] 2015-03-16 19:22
I have played with docker a bit, but the right thing to do isn't to add all the dependencies in the same container. Exceptionless would be a a single container with the app. Then you'd have to spin up more 3 containers (mongo, es and redis) and make all of that work. It's not an easy task, but it's doable

**Comment by niemyjski** [comment] 2015-03-16 20:59
What do you think the best thing would be todo? I'd like to have a powershell script that sets everything up. I'll be creating a 2.0 release hopefully today here on github that contains the compiled version of the site.

**Comment by niemyjski** [comment] 2015-03-16 21:00
I've never played with this on azure yet.. but is there a way to set up a "recipe" that would configure everything with a few clicks?

**Comment by luisrudge** [comment] 2015-03-16 22:18
You could use vagrant, which is more suitable for setting up huge infrastructure things. So you can setup everything inside one virtual machine. But, if you want to go with docker, you really should setup 5 containers (mongo, es, redis, api, webapp). This is more the 'docker way' of doing things.

**Comment by luisrudge** [comment] 2015-03-16 22:19
@niemyjski azure has an ubuntu machine with docker already, but you can just add a new ubuntu vm and run `curl -sSL https://get.docker.com/ubuntu/ | sudo sh`

**Comment by niemyjski** [comment] 2015-03-16 22:23
I still need to verify that the api runs on linux. I think it should but don't know.

**Comment by luisrudge** [comment] 2015-03-16 22:24
yeah. That's true

**Comment by niemyjski** [comment] 2015-03-23 21:02
I ran into issue running the api on linux due to mono runtime. I think we may need to wait until mono addresses this issue or we port the runtime to vnext.

**Comment by niemyjski** [comment] 2016-01-12 17:37
@Nonobis @luisrudge Would you mind looking into this further and see if they fixed the mono issues?

**Comment by niemyjski** [comment] 2016-04-02 21:35
I'm closing this as this is something we will look into once we move to asp.net core. We are also looking at the performance impact running in docker may have.

**Closed by niemyjski** 2016-04-02 21:35 UTC
Labels: enhancement, help wanted

**Comment by masaeedu** [comment] 2016-08-17 02:38
@niemyjski Do you have an issue tracking the work that is blocking this?

**Comment by niemyjski** [comment] 2016-08-17 03:26
Nope, this can't happen until we support .net core (getting lots closer but still a few months out. We need to move to elastic 5.x)

Get Outlook for iOS




On Tue, Aug 16, 2016 at 9:38 PM -0500, "Asad Saeeduddin" <notifications@github.com> wrote:












@niemyjski Do you have an issue tracking the work that is blocking this?

**Comment by Boggin** [comment] 2017-02-09 12:41
@niemyjski "move to elastic 5.x" :heavy_check_mark:

**Comment by niemyjski** [comment] 2017-02-10 17:37
Still some work todo but getting closer

**Comment by theooos** [comment] 2017-07-25 13:04
How has this been coming along? :)

**Comment by niemyjski** [comment] 2017-07-25 13:06
We haven't really focused on this too much. We need to port to .net core before this happens and we still have some dependencies that need to support it. I hope once .net core 2.0 is out, we'll be much much closer. We're working on getting all of our libs on .net core over time (The next one will be foundation parsers).

**Comment by tanushshukla** [comment] 2018-07-02 10:52
Looks like the exceptionless in on .net core right now. 
Has there been an update on this?

**Comment by niemyjski** [comment] 2018-07-02 11:51
We have a docker container registry that we are going to start shipping
releases on as well. We're finalizing the bits and want to make sure its
super easy to run everything on k8s.
Thanks
-Blake Niemyjski

**Comment by ejsmith** [comment] 2018-07-02 13:37
@tanushshukla if you take this [docker-compose.yml](https://github.com/exceptionless/Exceptionless/blob/feature/aspnet21/docker-compose.yml) file, you can just run `docker-compose up` and you will get the entire app running (API, jobs, UI, Redis, Elasticsearch). We will be moving to using these images soon, but we aren't there just yet.

**Comment by tanushshukla** [comment] 2018-07-02 13:48
> @tanushshukla if you take this docker-compose.yml file, you can just run docker-compose up and you will get the entire app running (API, jobs, UI, Redis, Elasticsearch). We will be moving to using these images soon, but we aren't there just yet.

Thanks, I'll try it out.

**Comment by Nonobis** [comment] 2018-07-03 07:41
great ! I will try it too :)

**Comment by tanushshukla** [comment] 2018-07-04 17:05
I believe this was supposed to run on Linux only. I have not yet tried on Linux though.

So, I had some issues running it on windows mostly with the elastic search.
First of all the image, this compose file refers to is: image: slideroom/elasticsearch:98
There is a problem with this image. This one runs the elastic search under root. This is no more a warning but an error. Elasticsearch cannot run under root. This was fixed by taking a newer version of the image, image: slideroom/elasticsearch:latest.

Now elasticsearch container runs but crashes with the error:

`failed to obtain node locks, tried [[/usr/share/elasticsearch/data/docker-cluster]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?


	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.3.0.jar:6.3.0]


	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.3.0.jar:6.3.0]


	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.3.0.jar:6.3.0]


	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.3.0.jar:6.3.0]


	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.3.0.jar:6.3.0]


	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.3.0.jar:6.3.0]


	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.3.0.jar:6.3.0]


Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/docker-cluster]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?`

Do you guys have a fix for this?


I also tried to replace the elastic search with Windows Nano Server image for Elasticsearch using the image located at:
https://github.com/sixeyed/dockerfiles-windows/tree/master/elasticsearch

Now, elastic search works but exceptionless is not able to communicate with it.
It's just hanging at "Unable to revive connection: http://elasticsearch:9200/"}

You guys had any joy with this running on windows?


Attaching my docker files for reference. I had to make some changes to it.
[docker-exceptionless.zip](https://github.com/exceptionless/Exceptionless/files/2163923/docker-exceptionless.zip)

**Comment by ejsmith** [comment] 2018-07-04 18:17
Yes, the images run on Linux. You are trying to run them on Windows docker with it switched to Linux mode, correct?

**Comment by tanushshukla** [comment] 2018-07-04 19:56
That's correct. I tried the hybrid mode(windows + linux containers) as well when I tried to use syed's elastic search for windows.

**Comment by ejsmith** [comment] 2018-07-04 20:30
One thing to be aware of is that Exceptionless requires Elasticsearch 5.6 currently and won't work with 6.x. I will give it a try on Windows and see what is going on.

**Comment by ejsmith** [comment] 2018-07-05 00:15
I just tried this on Windows with Docker running in Linux container mode and it worked perfectly.

**Comment by tanushshukla** [comment] 2018-07-05 16:40
Ok so now it works. I assume for some reason my docker had become "dirty" overtime. It had a lot of env. variables and other stuff. 

I tried to restart it, even reset to factory defaults but it didn't work.
I eventually had to uninstall it and install it back making sure I never switch to windows containers.
It now works. Thanks a lot for your help.

I am successfully able to log from .Net framework but not from .net core.

I am not able to find the documentation for using .net core with self-hosting. Can you please help me there?
As I need to specify the server URL, this is how I used it:

`
ExceptionlessClient exceptionlessClient = new ExceptionlessClient()
            {
                Configuration =
                {
                    ServerUrl = "http://localhost:5000",
                    ApiKey =  "8tj9h7GNzBPTDXp8dfgss4SwYC9vwf2fi2",
                }
            };
            app.UseExceptionless(exceptionlessClient);
`

For MVC, this works:
<exceptionless apiKey="8tj9h7GNzBPTDXp4dfgbn4SwYC9vwf2fi2" serverUrl="http://localhost:5000"/>


On a side note, email doesn't work as well. I did not even get a verification email. I'm assuming this is because of some settings missing in the web.config file. Does this mean I would need to build the images myself with those settings in the config file?

**Comment by ejsmith** [comment] 2018-07-05 16:54
There is a NuGet package for ASP.NET Core (https://www.nuget.org/packages/Exceptionless.AspNetCore/).

Here are the instructions:
https://github.com/exceptionless/Exceptionless.Net/tree/master/src/Platforms/Exceptionless.AspNetCore

As far as email sending, you will need to configure an SMTP server. You can do all configuration through environment variables in the docker-compose.yml file.

https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Settings.cs#L160-L171

**Comment by tanushshukla** [comment] 2018-07-05 17:12
Thanks a lot, got the logging working. 

I'll check about the emails now.

**Comment by tanushshukla** [comment] 2018-07-06 11:40
Ok, so some good news and bad news. It's almost working. I was able to push in the env variables and could see them set in the docker and getting logged as well. But when I actually send the email, it says the email was sent but I never receive it. I've checked junk and everything. That doesn't appear to be the problem.

I tried different email settings, different SMTP servers but I just don't get the email.

This is the log for MailMessage:

`
 [11:21:13 DBG] Dequeued item: 55ee7ac13bb54fc68c102fa4c3d9254b
jobs_1           | [11:21:13 INF] Processing MailMessage queue entry: 55ee7ac13bb54fc68c102fa4c3d9254b
jobs_1           | [11:21:13 INF] Sent message: to=noreply@exceptionless.io subject=[myemail@gmail.com] Exceptionless Account Confirmation
jobs_1           | [11:21:13 DBG] Queue MailMessage complete item: 55ee7ac13bb54fc68c102fa4c3d9254b
jobs_1           | [11:21:13 INF] Auto completed MailMessage queue entry: 55ee7ac13bb54fc68c102fa4c3d9254b
jobs_1           | [11:21:13 DBG] Job run MailMessageJob succeeded.
`

It's weird that it logs my email as a subject and to as "noreply@exceptionless.io". I have set up all of these env. variables: SmtpFrom, SmtpHost, SmtpPort, SmtpEncryption: StartTLS, SmtpUser, SmtpPassword. I've verified that as well.

Can you guys replicate this issue?

**Comment by ejsmith** [comment] 2018-07-06 12:40
You probably need to set the AppMode to Production. Otherwise it won’t allow emails to go out.

**Comment by tanushshukla** [comment] 2018-07-06 14:30
Yeah, that did cross my mind but running the app under production the emails were erroring out with the following exception:

`
 [14:10:17 INF] Processing MailMessage queue entry: 68eae07e92b34ef0a6026320261c74ca
jobs_1           | [14:10:18 WRN] Auto abandoned MailMessage queue entry: 68eae07e92b34ef0a6026320261c74ca
jobs_1           | [14:10:18 ERR] Job run MailMessageJob failed: An error occurred while attempting to establish an SSL or TLS connection.
jobs_1           |
jobs_1           | The SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:
jobs_1           | 1. The server is using a self-signed certificate which cannot be verified.
jobs_1           | 2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
jobs_1           | 3. The certificate presented by the server is expired or invalid.
jobs_1           |
jobs_1           | See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions.
jobs_1           | MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.
jobs_1           |
jobs_1           | The SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:
jobs_1           | 1. The server is using a self-signed certificate which cannot be verified.
jobs_1           | 2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
jobs_1           | 3. The certificate presented by the server is expired or invalid.
jobs_1           |
jobs_1           | See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'System.Net.Http.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libSystem.Net.Http.Native: No such file or directory
jobs_1           |    at Interop.Http.GetSslVersionDescription()
jobs_1           |    at Interop.HttpInitializer..cctor()
jobs_1           |    --- End of inner exception stack trace ---
jobs_1           |    at Interop.Http..cctor()
jobs_1           |    --- End of inner exception stack trace ---
jobs_1           |    at Interop.Http.EasyCreate()
`
I thought I would be doing something wrong.
So after spending few more hours, I have got the email working. 

It looks to be a .net core issue.
https://github.com/dotnet/corefx/issues/30003

I had to install curl manually in the containers using bash and restart it. The email started working afterwards.

Command:
`apk update; apk add curl`

One last thing, the links in the email still points to https://be.exceptionless.io. Can this be overwritten as well using env. variable?

Thanks a lot for all your help.

**Comment by niemyjski** [comment] 2018-07-30 14:14
Yes, you'd just need to configure the base url in the config / environment variable

**Comment by tanushshukla** [comment] 2018-07-30 14:49
yes, I figured that out. Thanks a lot. It has been running fine ever since.

**Comment by niemyjski** [comment] 2018-10-04 12:45
@Nonobis sorry for the late reply, did you find out how to do this?

**Comment by tanushshukla** [comment] 2018-10-05 08:50
[**@Nonobis**](https://github.com/Nonobis) commented on [13 Sep 2018, 10:32 BST](https://github.com/exceptionless/Exceptionless/issues/64#issuecomment-420944904 "2018-09-13T09:32:35Z - Replied by Github Reply Comments"):
> [@tanushshukla](https://github.com/tanushshukla) / [@niemyjski](https://github.com/niemyjski) : Could you post a sample for installing exceptionless with docker ?  
> 
> I can't find a sample for setting exceptionless config by environnment value... or access to config file ?  
> 
> Thanks guys :)

You need to add the env variables just like you do it for any other docker container.


 environment:
      AppMode: Production
      SmtpFrom: useremail@gmail.com
      SmtpHost: smtp.gmail.com
      SmtpPort: 587
      SmtpEncryption: StartTLS
      SmtpUser: user@email.com
      SmtpPassword: userpassword

Emails are only triggered if its Prod environment. 
The actual compose file is here:
https://github.com/exceptionless/Exceptionless/blob/master/docker-compose.yml

**Comment by Nonobis** [comment] 2018-10-08 10:07
@tanushshukla : Perfect thanks :)
