### ISSUE TITLE
Provide HTTP_X_FORWARDED_FOR if present

### ISSUE THREAD

**Issue by haliphax** [exceptionless/Exceptionless#346] opened 2017-12-29 14:53 UTC
In all of our exception reports, we see the remote address as the address of our load balancer. This could likely be resolved at the IIS level, but it would be awesome if Exceptionless could show the value of the HTTP_X_FORWARDED_FOR server variable if it's present. v2.4.836

**Comment by niemyjski** [comment] 2017-12-29 21:42
This is a duplicate of https://github.com/exceptionless/Exceptionless.Net/issues/77 (If it's not please let me know). We only show the remote address that was collected on the client. Could you please update your client and let us know how it's working out.

**Closed by niemyjski** 2017-12-29 21:42 UTC
