### ISSUE TITLE
is it a bug?

### ISSUE THREAD

**Issue by maobiwen** [exceptionless/Exceptionless#812] opened 2021-01-09 09:29 UTC
I run it with out docker 。
I download elasticsearch 7.10 ,run it ,then Run Exceptionless.Web 
I set RunJobsInProcess: true
then when I submit a exception ，the Exceptionless.Web show me this error，please help 。
my main code is in the end

System.ApplicationException: Error creating the index stage-events-v1-2021.01.09: Original: (400 - ElasticsearchClientException) Request failed to execute. Call: Status code 400 from: PUT /stage-events-v1-2021.01.09. ServerError: Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""
Server: (400) Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""

 ---> Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: PUT /stage-events-v1-2021.01.09. ServerError: Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""
   --- End of inner exception stack trace ---
   at Foundatio.Repositories.Elasticsearch.Configuration.Index.CreateIndexAsync(String name, Func`2 descriptor)
   at Foundatio.Repositories.Elasticsearch.Configuration.DailyIndex.EnsureDateIndexAsync(DateTime utcDate)
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.IndexDocumentsAsync(IReadOnlyCollection`1 documents, Boolean isCreateOperation, ICommandOptions options)
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.AddAsync(IEnumerable`1 documents, ICommandOptions options)
   at Exceptionless.Core.Pipeline.SaveEventAction.ProcessBatchAsync(ICollection`1 contexts) in D:\codes\fromgithub\Exceptionless-7.0.9\src\Exceptionless.Core\Pipeline\040_SaveEventAction.cs:line 23

main code picture 
![image](https://user-images.githubusercontent.com/11902441/104088289-a6b42180-52a0-11eb-8245-42d5bffd4316.png)

![image](https://user-images.githubusercontent.com/11902441/104088199-fba36800-529f-11eb-8ce7-abaf253d55bd.png)
![image](https://user-images.githubusercontent.com/11902441/104088205-0827c080-52a0-11eb-8c04-2f9c487cb3bb.png)
![image](https://user-images.githubusercontent.com/11902441/104088206-0eb63800-52a0-11eb-9fe6-af49495c3a40.png)
![image](https://user-images.githubusercontent.com/11902441/104088212-1a096380-52a0-11eb-9622-8a08b5203263.png)

**Comment by maobiwen** [comment] 2021-01-09 09:32
英文有点烂，有中国的朋友在用这个吗？
我没有用docker搭建，自己手动一个个搭建。
我下载了 Elasticsearch 7.10 运行后，确定 localhost:9200 可以访问。如下图
![image](https://user-images.githubusercontent.com/11902441/104088271-7ec4be00-52a0-11eb-8f94-e26340cd984e.png)

我都能在web控制台新增项目，获取apiKey了，但是发送异常去服务器的话，服务器显示写不进elasticsearch，感觉像是bug？

**Comment by niemyjski** [comment] 2021-01-11 14:32
Hello,

Thanks for reaching out to us. This is a duplicate of https://github.com/exceptionless/Exceptionless/issues/681. You need to ensure the mapper-size plugin is enabled or disable it via configuration as shown in #681

**Closed by niemyjski** 2021-01-11 14:32 UTC

**Comment by maobiwen** [comment] 2021-01-12 05:20
> Hello,
> 
> Thanks for reaching out to us. This is a duplicate of #681. You need to ensure the mapper-size plugin is enabled or disable it via configuration as shown in #681

Thank you .I had solve it

**Comment by zhangkeyuan** [comment] 2021-08-10 07:05
> > Hello,
> > Thanks for reaching out to us. This is a duplicate of #681. You need to ensure the mapper-size plugin is enabled or disable it via configuration as shown in #681
> 
> Thank you .I had solve it

咋解决的呀
