### ISSUE TITLE
creating index error

### ISSUE THREAD

**Issue by knowyi** [exceptionless/Exceptionless#815] opened 2021-01-11 09:46 UTC
Error creating the index prod-events-v1-2021.01.11: Original: (400 - ElasticsearchClientException) Request failed to execute. Call: Status code 400 from: PUT /prod-events-v1-2021.01.11. ServerError: Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters: [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters: [_size : {enabled=true}]

**Comment by knowyi** [comment] 2021-01-11 09:46
es version 7.4.0

**Comment by niemyjski** [comment] 2021-01-11 14:32
Hello,

Thanks for reaching out to us. This is a duplicate of https://github.com/exceptionless/Exceptionless/issues/681. You need to ensure the mapper-size plugin is enabled or disable it via configuration as shown in #681

**Closed by niemyjski** 2021-01-11 14:32 UTC

**Comment by niemyjski** [comment] 2021-01-12 02:53
Let me know if you have any questions or need any help. I'm curious how are you running and upgrading ES?

**Comment by knowyi** [comment] 2021-01-12 03:26
> 如果您有任何疑问或需要任何帮助，请告诉我。我很好奇您如何运行和升级ES？

At present, I am still in the testing stage, and I am not familiar with ES，Production will use Alibaba cloud's ES Service，Before I used ES 7.9.3, there was no problem. Since the highest version of Alibaba cloud ES is only 7.7, many strange problems occurred when I deployed es 7.4 locally

**Comment by knowyi** [comment] 2021-01-12 03:32
> 如果您有任何疑问或需要任何帮助，请告诉我。我很好奇您如何运行和升级ES？

I have deployed development mode and production mode to share local es7.4 services. The log can be collected normally, but the production mode exception notification cannot be sent normally. I'm still looking for problems

**Comment by knowyi** [comment] 2021-01-12 03:35
> 如果您有任何疑问或需要任何帮助，请告诉我。我很好奇您如何运行和升级ES？

This is my ES docker run command docker run -d --name es -p 9200:9200 -p 9300:9300 --restart=always -e ES_JAVA_OPTS="-Xms2g -Xmx2g" -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.7.0

**Comment by knowyi** [comment] 2021-01-12 03:35
> 如果您有任何疑问或需要任何帮助，请告诉我。我很好奇您如何运行和升级ES？
This is my es docker run command
docker run -d --name es -p 9200:9200 -p 9300:9300 --restart=always -e ES_JAVA_OPTS="-Xms2g -Xmx2g" -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.4.0

**Comment by knowyi** [comment] 2021-01-12 03:37
> Let me know if you have any questions or need any help. I'm curious how are you running and upgrading ES?

At present, I am still in the testing stage, and I am not familiar with ES，Production will use Alibaba cloud's ES Service，Before I used ES 7.9.3, there was no problem. Since the highest version of Alibaba cloud ES is only 7.7, many strange problems occurred when I deployed es 7.4 locally

I have deployed development mode and production mode to share local es7.4 services. The log can be collected normally, but the production mode exception notification cannot be sent normally. I'm still looking for problems

This is my es docker run command
docker run -d --name es -p 9200:9200 -p 9300:9300 --restart=always -e ES_JAVA_OPTS="-Xms2g -Xmx2g" -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.4.0

**Comment by niemyjski** [comment] 2021-01-12 04:24
I can't think of any problems running version 7.7 with your setup. You'll want at least 3 small nodes. If you are running a single node you'll want to set a query string`replicas=0` on the connection string for a single node: https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Configuration/ElasticsearchOptions.cs#L58
