### ISSUE TITLE
Upgrading in ASP.NET project from 2.0.1283 to 2.0.1288 leaves extra lines in packages.config

### ISSUE THREAD

**Issue by PhilipDn** [exceptionless/Exceptionless#80] opened 2015-03-30 21:47 UTC
[This is a minor issue.]

In an ASP.NET web forms application (.NET 4.5), I upgraded the Exceptionless client from v2.0.1283 to the latest (v2.0.1288), by clicking "Update All" in "Manage Nuget packages". This updated successfully, but left the "2.0.1283" lines in packages.config in addition to adding the lines for "2.0.1288". This has now happened in 2 separate projects.

Note: I edited the packages.config file after this update and built/published the application successfully.

In another project that was previously using v2.0.1277, doing an "Update All" upgraded to v2.0.1288 and did not leave any lines for older versions in packages.config.

**Comment by niemyjski** [comment] 2015-03-30 21:58
Is it one specific package that's getting duplicated?

**Comment by PhilipDn** [comment] 2015-03-30 23:12
It's both Exceptionless.Portable and Exceptionless.Web that are duplicated.

**Comment by niemyjski** [comment] 2015-03-30 23:58
I'll try to reproduce. It kind of sounds like a bug with Nuget.. Is it up to date?

**Comment by niemyjski** [comment] 2015-03-30 23:59
Are you right clicking on the project or solution level?

**Comment by PhilipDn** [comment] 2015-03-31 00:38
Right-click on the project (not the solution) in Visual Studio 2013, and select "Manage NuGet Packages...".

Visual Studio has Update 4 installed, all Visual Studio updates are installed, and all extensions are up-to-date. The NuGet Package Manager in Visual Studio is v2.8.50926.663 from Nov-12-2014.

**Comment by niemyjski** [comment] 2015-04-03 18:16
Can you see if the latest nuget release (released today) fixes this issue. I haven't been able to reproduce this issue.

**Comment by PhilipDn** [comment] 2015-04-06 18:28
Thanks for checking and attempting to reproduce this issue.

However, I was about to upgrade to the latest version, but I have a question about the version number. The latest version is 3.0.1300 (up from 2.0.1288). Should this have been version 2.* instead of 3.*?

I won't update to the latest client version yet.

**Comment by niemyjski** [comment] 2015-04-06 18:33
It's a major version because we broke some things as described in the upgrade docs (we renamed enrichments to plugins). If you weren't using custom enrichments then we didn't break you, if we did just change the words and one method signature. We have a blog post on plugins that will be released very soon :). Let me know what happens when you upgrade. If you could record it with jing as it happens that would be greatly appreciated.

**Comment by PhilipDn** [comment] 2015-04-07 16:58
The latest version is correctly upgraded using the NuGet package manager. Thanks.

**Comment by niemyjski** [comment] 2015-04-07 21:28
Thanks for the update.

**Closed by niemyjski** 2015-04-07 21:28 UTC
Labels: bug, Link <=> exceptionless/Exceptionless.Net
