### ISSUE TITLE
Email Notifications did not work

### ISSUE THREAD

**Issue by jakingfox** [exceptionless/Exceptionless#243] opened 2016-08-01 10:53 UTC
Hi.
I downloaded the latest version of Exceptionless and I setup my server following the tutorial for Self-hosting. But Email Notifications did not work, what am I missing ?

```
<mailSettings>
    <smtp from="xxxxx@gmail.com">
        <network host="smtp.gmail.com" port="587" userName="xxxxx@gmail.com" password="xxxxx" enableSsl="true" />
    </smtp>
</mailSettings>
```

![123](https://cloud.githubusercontent.com/assets/5730269/17291880/f95c728e-5818-11e6-942f-30117991d310.png)

**Comment by niemyjski** [comment] 2016-08-01 14:59
Are you using in process or out of process jobs (configured in your web.config)? Did you update your `WebSiteMode` to `Production`? I'm assuming your email address is verified? Are you getting any notifications at all?

**Comment by jakingfox** [comment] 2016-08-02 01:14
Thanks for your reply
The attachment is my Web.config 

I Only received the verification email after I created an account, Other email notifications did not receive.

```
  <appSettings>
    <!-- Base url for the ui used to build links in emails and other places. -->
    <add key="BaseURL" value="http://10.57.180.149:50000/#" />
    <!-- Controls whether SSL is required. Only enable this if you have SSL configured. -->
    <add key="EnableSSL" value="false" />
    <!--
    Dev: Use this mode when debugging. (Outbound emails restricted)
    QA: Use this mode when deployed to staging.  (Outbound emails restricted)
    Production: Use this mode when deployed to production.
    -->
    <add key="WebsiteMode" value="Production" />
    <!-- Email addresses that match this comma delimited list of domains and email addresses will be allowed to be sent out in Dev and QA mode -->
    <add key="AllowedOutboundAddresses" value="exceptionless.io,codesmithtools.com" />
    <!-- All emails that do not match the AllowedOutboundAddresses will be sent to this address in Dev and QA mode -->
    <add key="TestEmailAddress" value="xxxxx@gmail.com" />
    <!-- Controls whether users can signup. -->
    <add key="EnableAccountCreation" value="true" />
    <!-- Controls whether daily summary emails are sent -->
    <add key="EnableDailySummary" value="true" />
    <!-- Folder used to store event post data -->
    <add key="StorageFolder" value="|DataDirectory|\storage" />
    <!-- Runs the jobs in the current website process -->
    <add key="RunJobsInProcess" value="true" />
    <add key="aspnet:UseTaskFriendlySynchronizationContext" value="true" />
  </appSettings>
  <system.net>
    <mailSettings>
      <smtp from="xxxxx@gmail.com">
        <network host="smtp.gmail.com" port="587" userName="xxxxx@gmail.com" password="xxxxxx" enableSsl="true" />
      </smtp>
    </mailSettings>
    <defaultProxy enabled="true" />
  </system.net>
  <system.web>
    <authentication mode="None" />
    <compilation targetFramework="4.6" debug="false" />
    <httpRuntime targetFramework="4.6" maxUrlLength="1024" />
    <customErrors mode="RemoteOnly" />
  </system.web>
```

**Comment by niemyjski** [comment] 2016-08-03 13:34
All that looks good,  You could try pulling down the code locally and step through the mail sender or you could enable logging on the client. You can do this by creating a new exceptionless project and then add two new app keys

```xml
    <add key="Exceptionless:ApiKey" value="API_KEY_HERE" />
    <add key="Exceptionless:ServerUrl" value="http://ExceptionlessServerEndPoint" />
```

Then trigger a few new events and failed emails should appear in the logs.

**Comment by jakingfox** [comment] 2016-08-04 11:06
I think the reason is I use Nlog methods, that's why I do not receive any email notification. then I tried to use
`ExceptionlessClient.Default.SubmitLog("Logging made easy"); `
I was able to recieve email alerts.

My new question is, Can NLog supported mail notification?

Another problem is that, I tried to send error follow the example "Manually Sending Errors", I did not receive any notification and no error records
```
    try
    {
        throw new AggregateException("Unable to create order from quote.");
    }
    catch (Exception ex)
    {
        ex.ToExceptionless().Submit();
    }
```

**Comment by eric1973** [comment] 2016-08-04 11:54
I had the same issue. After deleting the whole stack (all exceptions, events, logs) I was able to receive emails again.

**Comment by niemyjski** [comment] 2016-08-04 13:34
I've added new instructions on how to view the log files of the exceptionless server (https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting#troubleshooting)

@jakingfox what do you mean? Everything is sent to exceptionless as an event, if the event reached us, it's a candidate for a notification, please note that only specific instances will trigger a notification (you will only get them for new events, critical events, and regressions), we won't ever send out emails for every occurrence.

Do you think this is the behavior you both hit?

**Comment by ericbrunner** [comment] 2016-08-05 01:38
Hey Blake,



That sentence is missleading:


Create a new exceptionless project and then add the following appSettings to theweb.config<https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/Web.config#L8>.


You link to the server side weg.config. But don't you mean the client projects app.config or

web.config? Because why should an API Key be added on the server side.


mit freundlichen Grüssen/Kind regards,
Erich Brunner
___________________________
Thomas-Morus Gasse 6/4/6
A-1130 Wien
mobil : +43-680-33-24-504
email : erich.brunner@live.at<http://live.at/>
github: https://github.com/ericbrunner
___________________________




________________________________
Von: Blake Niemyjski <notifications@github.com>
Gesendet: Donnerstag, 04. August 2016 15:34
An: exceptionless/Exceptionless
Cc: Eric Brunner; Comment
Betreff: Re: [exceptionless/Exceptionless] Email Notifications did not work (#243)


I've added new instructions on how to view the log files of the exceptionless server (https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting#troubleshooting)

@jakingfox<https://github.com/jakingfox> what do you mean? Everything is sent to exceptionless as an event, if the event reached us, it's a candidate for a notification, please note that only specific instances will trigger a notification (you will only get them for new events, critical events, and regressions), we won't ever send out emails for every occurrence.

Do you think this is the behavior you both hit?

-

**Comment by niemyjski** [comment] 2016-08-05 03:13
You are using exceptionless client which is hooked up to the exceptionless server to log to itself the server. So yes you need to create a new project on the server and then have the servers client to use that app key and server url.. This will allow you to view the server side logs using exceptionless ui

**Comment by jakingfox** [comment] 2016-08-09 10:03
Thank you for your reply, but i am confused.
if an exception occurrs 3 times are send to exceptionless in one day, how many times will exceptionless send out email ? 
if the same exception occurrs again the next day , will exceptionless send out email ?

**Comment by niemyjski** [comment] 2016-08-09 17:04
- once, we only send it on the first time it occurs.
- We send it out every time if it's marked as a critical exception (within reason, we only send out 15 notifications in like a 15 minute window).
- If you mark a stack as fixed, and it regresses (new occurrence in a newer version), we will send one regression email.

**Comment by niemyjski** [comment] 2016-08-09 17:06
We don't believe that we should ever send out an email for every occurrence that occurs. This is noise and you will start ignoring every email and they will not be as important. **But we do want to be smarter about emails** and send one out if you start getting a ton of occurrences to let you know that something is going wrong. 

With the above said, is this working as expected?

**Comment by jakingfox** [comment] 2016-08-10 01:59
Thanks for all your help, the process of exceptionless is reasonable, i will use it to replace elmah.

**Comment by niemyjski** [comment] 2016-08-10 14:16
Thanks, If you have any questions or this didn't resolve this issue, please let us know and we will reopen this issue.

**Closed by niemyjski** 2016-08-10 14:16 UTC
Labels: investigating
