### ISSUE TITLE
not log

### ISSUE THREAD

**Issue by yun6cc** [exceptionless/Exceptionless#768] opened 2020-11-07 02:27 UTC
When the amount of access is large, REDIS DB0 has a lot of cache keys, then no log is recorded, and FlushDB is required to re-record the log.

**Comment by niemyjski** [comment] 2020-11-07 12:11
Can you please provide more information and how to reproduce. What are in the event processor logs when this happens can you please provide some logs of this behavior and also possibly debug it? What version of redis are you using?

**Comment by yun6cc** [comment] 2020-11-08 01:40
Hello, thanks for your reply. The following is the relevant information about Redis on my side. As you can see, there are more than 200,000 keys now, and no logs are recorded anymore. It needs my FlushDB to log normally.
# Server
redis_version:3.0.501
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:ba05b51e58eb9205
redis_mode:standalone
os:Windows  
arch_bits:64
multiplexing_api:WinSock_IOCP
process_id:9656
run_id:fcf97de4218ce4f9d966491af900a08c8275b682
tcp_port:6379
uptime_in_seconds:4399320
uptime_in_days:50
hz:10
lru_clock:10963773
config_file:D:\tools\redis\redis.windows-service.conf

# Clients
connected_clients:3141
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:173297032
used_memory_human:165.27M
used_memory_rss:173259264
used_memory_peak:408797776
used_memory_peak_human:389.86M
used_memory_lua:43008
mem_fragmentation_ratio:1.00
mem_allocator:jemalloc-3.6.0

# Persistence
loading:0
rdb_changes_since_last_save:10446
rdb_bgsave_in_progress:0
rdb_last_save_time:1604799242
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:1
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok

# Stats
total_connections_received:11172
total_commands_processed:791010699
instantaneous_ops_per_sec:713
total_net_input_bytes:75510700079
total_net_output_bytes:692741007191
instantaneous_input_kbps:76.18
instantaneous_output_kbps:449.07
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:5835660
evicted_keys:0
keyspace_hits:274722628
keyspace_misses:160420492
pubsub_channels:8
pubsub_patterns:0
latest_fork_usec:13914
migrate_cached_sockets:0

# Replication
role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:8893.75
used_cpu_user:7545.44
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=222540,expires=222380,avg_ttl=537622653
db1:keys=6,expires=0,avg_ttl=0
db2:keys=95,expires=0,avg_ttl=0
db3:keys=1,expires=0,avg_ttl=0
db5:keys=7,expires=0,avg_ttl=0
db6:keys=108,expires=108,avg_ttl=28827772
db9:keys=49,expires=0,avg_ttl=0
db12:keys=1,expires=0,avg_ttl=0
db22:keys=2,expires=0,avg_ttl=0
db33:keys=17,expires=0,avg_ttl=0
db34:keys=29,expires=0,avg_ttl=0
db35:keys=3,expires=0,avg_ttl=0
db36:keys=55,expires=0,avg_ttl=0
db40:keys=3,expires=0,avg_ttl=0
db122:keys=2,expires=0,avg_ttl=0
db125:keys=2,expires=0,avg_ttl=0
db131:keys=1,expires=1,avg_ttl=16331741
db133:keys=7,expires=0,avg_ttl=0

**Comment by niemyjski** [comment] 2020-11-08 19:50
Is the event posts job running? What are the logs for that? What is taking up the most keys? is it `q:eventposts`?

**Comment by yun6cc** [comment] 2020-11-09 01:34
job is running.
keys is it q:eventposts

**Comment by niemyjski** [comment] 2020-11-09 03:27
Can you send some of the logs for that job? Is it running into errors. The reason that queue is so large is due to the job isn't picking work items off of it fast enough or there is a configuration errors. It doesn't make any sense that you need to reset redis to get this to work, if anything you need more job processors.

**Comment by yun6cc** [comment] 2020-11-09 03:55
How should multiple job be deployed?

**Comment by niemyjski** [comment] 2020-11-09 04:26
Depends on how you are running it, how are you hosting it? Also please provide the docker job logs.

**Comment by yun6cc** [comment] 2020-11-15 10:39
Hello, after hearing that you need to create multiple jobs, I changed docker-compose to the following content, can you see it?
![321](https://user-images.githubusercontent.com/17695936/99182760-ee6f6e80-2771-11eb-92ae-970612f2f0ee.png)
![123](https://user-images.githubusercontent.com/17695936/99182763-efa09b80-2771-11eb-94c4-3669e0c436f4.png)

**Comment by niemyjski** [comment] 2020-11-15 14:41
Can you please provide the docker job logs when it stops processing.

**Comment by niemyjski** [comment] 2021-05-19 11:52
I'm going to close this until more logs / data is provided so we can diagnose this. It would be nice to get to the bottom of this but we also haven't seen this behavior so if you can provide more information we will reopen this.

**Closed by niemyjski** 2021-05-19 11:52 UTC
Labels: awaiting reply
