### ISSUE TITLE
not seeing logout button

### ISSUE THREAD

**Issue by Nonobis** [exceptionless/Exceptionless#129] opened 2015-08-07 07:49 UTC
Hi,

i am on v2.1.511 on a w2k2012, all working but i cant find the logout  button ?
![2015-08-07 09_47_13-exceptionless](https://cloud.githubusercontent.com/assets/3251510/9131170/89748f7e-3ce9-11e5-9f35-d3e39b14a6e6.png)

Maybe a missing settings ?
Thanks for your help

**Comment by niemyjski** [comment] 2015-08-07 13:29
![image](https://cloud.githubusercontent.com/assets/1020579/9136718/718d519e-3cde-11e5-9d1c-27e358c41c74.png)

You need to click on your name in the upper right. How do you think we can make this more discoverable?

**Comment by Nonobis** [comment] 2015-08-07 14:31
@niemyjski : ok, ... my problem ... i don't have the icon on my install ... see my screenshot on first post

![2015-08-07 16_29_45-exceptionless](https://cloud.githubusercontent.com/assets/3251510/9137999/b0f6fc66-3d21-11e5-84c5-7ea12e03d20a.png)

**Comment by Nonobis** [comment] 2015-08-07 21:32
@niemyjski : the 'account" button is only visble on IE, not on firefox ... maybe a css problem ?

**Comment by niemyjski** [comment] 2015-08-08 19:25
Yeah I think so, I'll check it out

**Comment by niemyjski** [comment] 2015-08-10 19:06
I'm not sure what the issue is, maybe you are blocking [gravatar.com](gravatar.com)? It shows up for me on every browser. Can you check this and reopen this issue if this site is not being blocked.

**Comment by Nonobis** [comment] 2015-08-10 19:15
@niemyjski : i have find the problem .... i have an extension in firefox 'Ghostery' for removing ads ....apparently it's blocking gravatar ... i have added my instance in white list and it's working. Thanks for the tip !

**Comment by niemyjski** [comment] 2015-08-10 19:40
No problem, I'm wondering if we should add some kind of placeholder there under the image? Just so people know there is a menu.. Would you mind doing a pull request for this?

**Comment by Nonobis** [comment] 2015-08-10 19:57
i will try to understand the code and maybe make  a pr. i am more of classic asp.net kind of guy for now ... i have little exp with the next gen framework.

**Comment by niemyjski** [comment] 2015-08-24 20:24
I'm going to close this issue, but feel free to do a pull request for this if you wish.

**Closed by niemyjski** 2015-08-24 20:24 UTC
