### ISSUE TITLE
I can't build 6.0.0

### ISSUE THREAD

**Issue by yaoxiadu** [exceptionless/Exceptionless#618] opened 2020-05-12 03:14 UTC
/usr/share/dotnet/sdk/3.1.201/NuGet.targets(124,5): error : Unable to load the service index for source https://f.feedz.io/foundatio/foundatio/nuget/index.json. [/app/Exceptionless.sln]
/usr/share/dotnet/sdk/3.1.201/NuGet.targets(124,5): error :   Resource temporarily unavailable [/app/Exceptionless.sln]
ERROR: Service 'api' failed to build: The command '/bin/sh -c dotnet restore' returned a non-zero code: 1

**Comment by ejsmith** [comment] 2020-05-12 04:37
Seems to be a pretty common thing. It seems like https://feedz.io is blocked in some areas. Most of the time we aren't using that feed so it's not necessary, but I don't really want to remove it either. Would be nice if we could figure out how to make it optional and not error out if it's not reachable.

**Comment by niemyjski** [comment] 2020-05-12 11:58
This is a duplicate of #613. I'm not sure how we would make it optional when only the artifacts are on there. A part of me says we should never merge to master with our own nightly builds.

**Closed by niemyjski** 2020-05-12 11:58 UTC
