### ISSUE TITLE
为什么测试环境一切正常，而正式环境无法监测到日志

### ISSUE THREAD

**Issue by ysq5202121** [exceptionless/Exceptionless#871] opened 2021-04-14 06:17 UTC
Hello, Dashen. I've been in big trouble for a few days. I hope I can help. The error log can't be detected under the official environment of Windows Server 2012 IIS
------------------------------------------------------------------------------------------------------------------------------------

{
  "informational_version": "1.0.0",
  "app_mode": "Production",
  "machine_name": "5-11-2016SERVER"
}
{
  "cluster_name" : "elasticsearch",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 23,
  "active_shards" : 23,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 7,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 76.66666666666667
}
上面是相关服务器状态

**Comment by ysq5202121** [comment] 2021-04-14 06:54
![image](https://user-images.githubusercontent.com/8586973/114666712-22ef5280-9d31-11eb-9020-0263eff0b37d.png)
Prod 一直没有shuj数据
Dev 在测试下面有数据，
请用谷歌页面翻译，谢谢！！

**Comment by ysq5202121** [comment] 2021-04-14 06:56
![image](https://user-images.githubusercontent.com/8586973/114667040-92654200-9d31-11eb-8012-a3a2dc3c35e0.png)
![image](https://user-images.githubusercontent.com/8586973/114667085-a01ac780-9d31-11eb-8a62-0689a096b84b.png)

**Comment by ysq5202121** [comment] 2021-04-14 07:05
另外如何在服务器开启输出日志文件

**Comment by niemyjski** [comment] 2021-04-14 13:10
Hello,

I'm not sure what exactly you are asking other than your Elastic instance is Yellow. This is a bit outside of the scope of this project but probably has to do with shard count and running a single node.

**Comment by ysq5202121** [comment] 2021-04-15 08:15
> Hello,
> 
> I'm not sure what exactly you are asking other than your Elastic instance is Yellow. This is a bit outside of the scope of this project but probably has to do with shard count and running a single node.

![image](https://user-images.githubusercontent.com/8586973/114837016-d3c72180-9e05-11eb-8436-878260ef7dd5.png)

**Comment by ysq5202121** [comment] 2021-04-15 09:35
缺少mapper-size 插件

**Comment by niemyjski** [comment] 2021-04-15 12:21
Thanks for reaching out to us. This is a duplicate of #681. You need to ensure the mapper-size plugin is enabled or disable it via configuration as shown in #681

**Closed by niemyjski** 2021-04-15 12:21 UTC
