### ISSUE TITLE
Cannot find the added project after adding the project

### ISSUE THREAD

**Issue by Amber-Wish** [exceptionless/Exceptionless#739] opened 2020-10-09 09:49 UTC
After deploying with dockerfile, I can register and log in normally, and add organizations.However, when adding a project, the project information just added will always be lost.
![image](https://user-images.githubusercontent.com/55867470/95568982-81bcd200-0a57-11eb-9293-ef15564bada4.png)
After the addition is successful, the added information cannot be found in the list.
![image](https://user-images.githubusercontent.com/55867470/95569040-98632900-0a57-11eb-94a5-17ebe0b1a60d.png)

**Comment by Amber-Wish** [comment] 2020-10-09 09:50
But I see the added data in redis, what is the situation?
![image](https://user-images.githubusercontent.com/55867470/95569298-f42db200-0a57-11eb-8c44-3ca84e423efc.png)

**Comment by Amber-Wish** [comment] 2020-10-09 09:52
How should I solve this problem? Looking forward to reply.

**Comment by niemyjski** [comment] 2020-10-12 14:17
Hello,

Thanks for reaching out to us, is there anything in your docker logs?

**Comment by niemyjski** [comment] 2020-10-14 11:38
Also, what do you mean by always lost? Is it still in the project index in Elasticsearch?

**Comment by Amber-Wish** [comment] 2020-10-15 08:31
@niemyjski Sorry for taking so long to reply. I can query the project information I added from kibana, but there is still no project on Exceptionless.
![image](https://user-images.githubusercontent.com/55867470/96097623-c3d88e80-0f03-11eb-8a5a-b5a4ca7743eb.png)
![image](https://user-images.githubusercontent.com/55867470/96097693-db177c00-0f03-11eb-80da-b70b9402b55d.png)

**Comment by niemyjski** [comment] 2020-10-15 11:23
If you added it from kibana it probably doesn't match existing data. You need to ensure user ids on notification settings match up and more importantly the organization id matches up with your existing organization id. I'm wondering if it has to do with issue #722 as well.

**Comment by Amber-Wish** [comment] 2020-10-16 05:41
I just added the following code to my dockerfile:`RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
&& echo 'Asia/Shanghai' >/etc/timezone`
Now, the problem is the same as the issue #722

**Comment by niemyjski** [comment] 2020-10-16 13:33
Thanks, I'm still digging into this, I had lots of tooling issues which were due to .net 5 rc1 and fixed in rc2. I'm going to add some timezone tests to this as well.

**Comment by niemyjski** [comment] 2020-10-18 17:39
I'm closing this as this is a dupe of #722 I'm currently working on a fix

**Closed by niemyjski** 2020-10-18 17:39 UTC
Labels: Hacktoberfest, bug, help wanted, investigating

**Comment by niemyjski** [comment] 2020-10-18 18:24
I just committed a fix for this, can you please try the nightly ci images and let me know how it works for you. I'll then tag a release.

**Comment by Amber-Wish** [comment] 2020-10-19 01:59
Thanks, but I don’t know how to use the nightly ci images.

**Comment by niemyjski** [comment] 2020-10-19 14:08
We pushed a release out so you don't have to. But in the future you'd just append `-ci` to the docker image name.
