### ISSUE TITLE
Very big "Message" is cut off using ellipsis

### ISSUE THREAD

**Issue by dampee** [exceptionless/Exceptionless#135] opened 2015-08-15 14:15 UTC
Having an easy way to copy (or view) the complete message would be easier.  Now we need to do an 'inspect element' in the browser.  

Copy of the complete message in a textArea (in a dialog) would be perfect.

**Comment by niemyjski** [comment] 2015-08-21 17:17
I'm going to be working on this soon. I want to be able to click on any field to have it expand.

**Comment by niemyjski** [comment] 2016-01-12 17:25
Closing this as a duplicate of https://github.com/exceptionless/Exceptionless.UI/issues/56 , We will be improving this in the next release.

**Closed by niemyjski** 2016-01-12 17:25 UTC
Labels: bug
