### ISSUE TITLE
After upgrading 6.0, the api service started abnormally in the docker environment.

### ISSUE THREAD

**Issue by yun6cc** [exceptionless/Exceptionless#559] opened 2020-03-26 01:26 UTC
After upgrading 6.0, the api service started abnormally in the docker environment.
![image](https://user-images.githubusercontent.com/17695936/77600765-cbbeea00-6f43-11ea-84e1-263e9008eb7b.png)
following is the error message.

`api_1            | [01:17:18 INF] Found 7 registered startup action(s).
api_1            | [01:17:18 INF] Running ["WaitForHealthChecks"] (priority -100) startup action...
api_1            | [01:17:18 INF] Hosting environment: Production
api_1            | [01:17:18 INF] Content root path: /app
api_1            | [01:17:18 INF] Now listening on: http://[::]:80
api_1            | [01:17:18 INF] Application started. Press Ctrl+C to shut down.
api_1            | [01:17:18 INF] Completed ["WaitForHealthChecks"] startup action in 00:00.
api_1            | [01:17:18 INF] Running ["ExceptionlessElasticConfiguration"] (priority 1) startup action...
api_1            | [01:17:19 ERR] Error creating index stacks-v1
api_1            | Server Error (Index=null Type=mapper_parsing_exception): Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [stacks : {include_in_all=false, dynamic=false, properties={references={include_in_all=true, type=text}, date_fixed={type=date}, total_occurrences={type=integer}, is_hidden={type=boolean}, is_regressed={type=boolean}, description={include_in_all=true, type=text}, type={type=keyword}, title={include_in_all=true, boost=1.1, type=text}, updated_utc={type=date}, tags={include_in_all=true, boost=1.2, type=text, fields={keyword={ignore_above=256, type=keyword}}}, first_occurrence={type=date}, last_occurrence={type=date}, occurrences_are_critical={type=boolean}, project_id={type=keyword}, organization_id={type=keyword}, fixed={type=boolean}, fixed_in_version={type=keyword}, id={type=keyword}, created_utc={type=date}, signature_hash={type=keyword}}}]
api_1            | [400] PUT /stacks-v1
api_1            | {"aliases":{"stacks":{}},"mappings":{"stacks":{"dynamic":false,"include_in_all":false,"properties":{"id":{"type":"keyword"},"created_utc":{"type":"date"},"updated_utc":{"type":"date"},"organization_id":{"type":"keyword"},"project_id":{"type":"keyword"},"signature_hash":{"type":"keyword"},"type":{"type":"keyword"},"first_occurrence":{"type":"date"},"last_occurrence":{"type":"date"},"title":{"type":"text","boost":1.1,"include_in_all":true},"description":{"type":"text","include_in_all":true},"tags":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}},"boost":1.2,"include_in_all":true},"references":{"type":"text","include_in_all":true},"date_fixed":{"type":"date"},"fixed":{"type":"boolean"},"fixed_in_version":{"type":"keyword"},"is_hidden":{"type":"boolean"},"is_regressed":{"type":"boolean"},"occurrences_are_critical":{"type":"boolean"},"total_occurrences":{"type":"integer"}}}},"settings":{"index.number_of_replicas":1,"index.priority":5,"index.number_of_shards":1}}
api_1            | [01:17:19 ERR] Error running ExceptionlessElasticConfiguration startup action: Error creating index stacks-v1: Server: (400) Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [stacks : {include_in_all=false, dynamic=false, properties={references={include_in_all=true, type=text}, date_fixed={type=date}, total_occurrences={type=integer}, is_hidden={type=boolean}, is_regressed={type=boolean}, description={include_in_all=true, type=text}, type={type=keyword}, title={include_in_all=true, boost=1.1, type=text}, updated_utc={type=date}, tags={include_in_all=true, boost=1.2, type=text, fields={keyword={ignore_above=256, type=keyword}}}, first_occurrence={type=date}, last_occurrence={type=date}, occurrences_are_critical={type=boolean}, project_id={type=keyword}, organization_id={type=keyword}, fixed={type=boolean}, fixed_in_version={type=keyword}, id={type=keyword}, created_utc={type=date}, signature_hash={type=keyword}}}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [stacks : {include_in_all=false, dynamic=false, properties={references={include_in_all=true, type=text}, date_fixed={type=date}, total_occurrences={type=integer}, is_hidden={type=boolean}, is_regressed={type=boolean}, description={include_in_all=true, type=text}, type={type=keyword}, title={include_in_all=true, boost=1.1, type=text}, updated_utc={type=date}, tags={include_in_all=true, boost=1.2, type=text, fields={keyword={ignore_above=256, type=keyword}}}, first_occurrence={type=date}, last_occurrence={type=date}, occurrences_are_critical={type=boolean}, project_id={type=keyword}, organization_id={type=keyword}, fixed={type=boolean}, fixed_in_version={type=keyword}, id={type=keyword}, created_utc={type=date}, signature_hash={type=keyword}}}]""
api_1            | 
api_1            | System.ApplicationException: Error creating index stacks-v1: Server: (400) Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [stacks : {include_in_all=false, dynamic=false, properties={references={include_in_all=true, type=text}, date_fixed={type=date}, total_occurrences={type=integer}, is_hidden={type=boolean}, is_regressed={type=boolean}, description={include_in_all=true, type=text}, type={type=keyword}, title={include_in_all=true, boost=1.1, type=text}, updated_utc={type=date}, tags={include_in_all=true, boost=1.2, type=text, fields={keyword={ignore_above=256, type=keyword}}}, first_occurrence={type=date}, last_occurrence={type=date}, occurrences_are_critical={type=boolean}, project_id={type=keyword}, organization_id={type=keyword}, fixed={type=boolean}, fixed_in_version={type=keyword}, id={type=keyword}, created_utc={type=date}, signature_hash={type=keyword}}}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [stacks : {include_in_all=false, dynamic=false, properties={references={include_in_all=true, type=text}, date_fixed={type=date}, total_occurrences={type=integer}, is_hidden={type=boolean}, is_regressed={type=boolean}, description={include_in_all=true, type=text}, type={type=keyword}, title={include_in_all=true, boost=1.1, type=text}, updated_utc={type=date}, tags={include_in_all=true, boost=1.2, type=text, fields={keyword={ignore_above=256, type=keyword}}}, first_occurrence={type=date}, last_occurrence={type=date}, occurrences_are_critical={type=boolean}, project_id={type=keyword}, organization_id={type=keyword}, fixed={type=boolean}, fixed_in_version={type=keyword}, id={type=keyword}, created_utc={type=date}, signature_hash={type=keyword}}}]""
api_1            | 
api_1            |    at Foundatio.Repositories.Elasticsearch.Configuration.IndexBase.CreateIndexAsync(String name, Func`2 descriptor)
api_1            |    at Foundatio.Repositories.Elasticsearch.Configuration.VersionedIndex.ConfigureAsync()
api_1            |    at Foundatio.Repositories.Elasticsearch.Configuration.ElasticConfiguration.ConfigureIndexesAsync(IEnumerable`1 indexes, Boolean beginReindexingOutdated)
api_1            |    at Foundatio.Hosting.Startup.StartupActionRegistration.RunAsync(IServiceProvider serviceProvider, CancellationToken shutdownToken)
api_1            |    at Foundatio.Hosting.Startup.StartupExtensions.<>c__DisplayClass0_1.<<RunStartupActionsAsync>b__3>d.MoveNext()
api_1            | [01:17:19 INF] Application is shutting down...
exless_api_1 exited with code 0
`

**Comment by gebiWangshushu** [comment] 2020-03-31 16:50
hello ~  got same issues, how to solved？

**Comment by niemyjski** [comment] 2020-03-31 22:28
What operating system are you running the docker commands on? Are you just using the docker-compose file from master?

**Comment by gebiWangshushu** [comment] 2020-04-01 02:17
CentOS Linux release 7.6.1810 (Core)， appreciated！

**Comment by gebiWangshushu** [comment] 2020-04-01 02:54
this's my  error message.thankyou!

[15:51:16 WRN] Metrics reporting is NOT enabled on 231f5f7f8aa9.
[15:51:18 INF] All new indexes will be created with 1 Shards and 1 Replicas
[15:51:18 INF] Found 7 registered startup action(s).
[15:51:19 INF] Running ["WaitForHealthChecks"] (priority -100) startup action...
[15:51:19 INF] Hosting environment: Production
[15:51:19 INF] Content root path: /app
[15:51:19 INF] Now listening on: http://[::]:80
[15:51:19 INF] Application started. Press Ctrl+C to shut down.
[15:51:19 ERR] Health check Elasticsearch completed after 638.2111ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:20 ERR] Health check Elasticsearch completed after 14.5986ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:21 ERR] Health check Elasticsearch completed after 5.7609ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:22 ERR] Health check Elasticsearch completed after 5.0644ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:23 ERR] Health check Elasticsearch completed after 5.4158ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:24 ERR] Health check Elasticsearch completed after 5.4745ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:25 ERR] Health check Elasticsearch completed after 9.4288ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:26 ERR] Health check Elasticsearch completed after 4.0841ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:27 ERR] Health check Elasticsearch completed after 4.121ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:28 ERR] Health check Elasticsearch completed after 5.0797ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:29 ERR] Health check Elasticsearch completed after 8.6144ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:30 ERR] Health check Elasticsearch completed after 7.3896ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:31 ERR] Health check Elasticsearch completed after 4.6288ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:32 ERR] Health check Elasticsearch completed after 6.6988ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:33 ERR] Health check Elasticsearch completed after 4.7802ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:34 ERR] Health check Elasticsearch completed after 5.6356ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:35 ERR] Health check Elasticsearch completed after 4.5657ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:36 ERR] Health check Elasticsearch completed after 5.6514ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:37 ERR] Health check Elasticsearch completed after 4.2188ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:39 ERR] Health check Elasticsearch completed after 6.0139ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:40 ERR] Health check Elasticsearch completed after 4.4139ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:41 ERR] Health check Elasticsearch completed after 7.4378ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:42 ERR] Health check Elasticsearch completed after 10.1242ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:43 ERR] Health check Elasticsearch completed after 2.8176ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:44 ERR] Health check Elasticsearch completed after 3.5227ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:45 ERR] Health check Elasticsearch completed after 8.7828ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:46 ERR] Health check Elasticsearch completed after 5.1383ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:47 ERR] Health check Elasticsearch completed after 10.3961ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:48 ERR] Health check Elasticsearch completed after 3.1517ms with status Unhealthy and 'Elasticsearch Ping Failed'
[15:51:50 INF] Completed ["WaitForHealthChecks"] startup action in 00:31.
[15:51:50 INF] Running ["ExceptionlessElasticConfiguration"] (priority 1) startup action...
[15:51:51 ERR] Error creating index stacks-v1
Server Error (Index=null Type=mapper_parsing_exception): Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [stacks : {include_in_all=false, dynamic=false, properties={references={include_in_all=true, type=text}, date_fixed={type=date}, total_occurrences={type=integer}, is_hidden={type=boolean}, is_regressed={type=boolean}, description={include_in_all=true, type=text}, type={type=keyword}, title={include_in_all=true, boost=1.1, type=text}, updated_utc={type=date}, tags={include_in_all=true, boost=1.2, type=text, fields={keyword={ignore_above=256, type=keyword}}}, first_occurrence={type=date}, last_occurrence={type=date}, occurrences_are_critical={type=boolean}, project_id={type=keyword}, organization_id={type=keyword}, fixed={type=boolean}, fixed_in_version={type=keyword}, id={type=keyword}, created_utc={type=date}, signature_hash={type=keyword}}}]
[400] PUT /stacks-v1
{"aliases":{"stacks":{}},"mappings":{"stacks":{"dynamic":false,"include_in_all":false,"properties":{"id":{"type":"keyword"},"created_utc":{"type":"date"},"updated_utc":{"type":"date"},"organization_id":{"type":"keyword"},"project_id":{"type":"keyword"},"signature_hash":{"type":"keyword"},"type":{"type":"keyword"},"first_occurrence":{"type":"date"},"last_occurrence":{"type":"date"},"title":{"type":"text","boost":1.1,"include_in_all":true},"description":{"type":"text","include_in_all":true},"tags":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}},"boost":1.2,"include_in_all":true},"references":{"type":"text","include_in_all":true},"date_fixed":{"type":"date"},"fixed":{"type":"boolean"},"fixed_in_version":{"type":"keyword"},"is_hidden":{"type":"boolean"},"is_regressed":{"type":"boolean"},"occurrences_are_critical":{"type":"boolean"},"total_occurrences":{"type":"integer"}}}},"settings":{"index.number_of_replicas":1,"index.priority":5,"index.number_of_shards":1}}

[15:51:51 ERR] Error running ExceptionlessElasticConfiguration startup action: Error creating index stacks-v1: Server: (400) Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [stacks : {include_in_all=false, dynamic=false, properties={references={include_in_all=true, type=text}, date_fixed={type=date}, total_occurrences={type=integer}, is_hidden={type=boolean}, is_regressed={type=boolean}, description={include_in_all=true, type=text}, type={type=keyword}, title={include_in_all=true, boost=1.1, type=text}, updated_utc={type=date}, tags={include_in_all=true, boost=1.2, type=text, fields={keyword={ignore_above=256, type=keyword}}}, first_occurrence={type=date}, last_occurrence={type=date}, occurrences_are_critical={type=boolean}, project_id={type=keyword}, organization_id={type=keyword}, fixed={type=boolean}, fixed_in_version={type=keyword}, id={type=keyword}, created_utc={type=date}, signature_hash={type=keyword}}}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [stacks : {include_in_all=false, dynamic=false, properties={references={include_in_all=true, type=text}, date_fixed={type=date}, total_occurrences={type=integer}, is_hidden={type=boolean}, is_regressed={type=boolean}, description={include_in_all=true, type=text}, type={type=keyword}, title={include_in_all=true, boost=1.1, type=text}, updated_utc={type=date}, tags={include_in_all=true, boost=1.2, type=text, fields={keyword={ignore_above=256, type=keyword}}}, first_occurrence={type=date}, last_occurrence={type=date}, occurrences_are_critical={type=boolean}, project_id={type=keyword}, organization_id={type=keyword}, fixed={type=boolean}, fixed_in_version={type=keyword}, id={type=keyword}, created_utc={type=date}, signature_hash={type=keyword}}}]""

System.ApplicationException: Error creating index stacks-v1: Server: (400) Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [stacks : {include_in_all=false, dynamic=false, properties={references={include_in_all=true, type=text}, date_fixed={type=date}, total_occurrences={type=integer}, is_hidden={type=boolean}, is_regressed={type=boolean}, description={include_in_all=true, type=text}, type={type=keyword}, title={include_in_all=true, boost=1.1, type=text}, updated_utc={type=date}, tags={include_in_all=true, boost=1.2, type=text, fields={keyword={ignore_above=256, type=keyword}}}, first_occurrence={type=date}, last_occurrence={type=date}, occurrences_are_critical={type=boolean}, project_id={type=keyword}, organization_id={type=keyword}, fixed={type=boolean}, fixed_in_version={type=keyword}, id={type=keyword}, created_utc={type=date}, signature_hash={type=keyword}}}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [stacks : {include_in_all=false, dynamic=false, properties={references={include_in_all=true, type=text}, date_fixed={type=date}, total_occurrences={type=integer}, is_hidden={type=boolean}, is_regressed={type=boolean}, description={include_in_all=true, type=text}, type={type=keyword}, title={include_in_all=true, boost=1.1, type=text}, updated_utc={type=date}, tags={include_in_all=true, boost=1.2, type=text, fields={keyword={ignore_above=256, type=keyword}}}, first_occurrence={type=date}, last_occurrence={type=date}, occurrences_are_critical={type=boolean}, project_id={type=keyword}, organization_id={type=keyword}, fixed={type=boolean}, fixed_in_version={type=keyword}, id={type=keyword}, created_utc={type=date}, signature_hash={type=keyword}}}]""

   at Foundatio.Repositories.Elasticsearch.Configuration.IndexBase.CreateIndexAsync(String name, Func`2 descriptor)
   at Foundatio.Repositories.Elasticsearch.Configuration.VersionedIndex.ConfigureAsync()
   at Foundatio.Repositories.Elasticsearch.Configuration.ElasticConfiguration.ConfigureIndexesAsync(IEnumerable`1 indexes, Boolean beginReindexingOutdated)
   at Foundatio.Hosting.Startup.StartupActionRegistration.RunAsync(IServiceProvider serviceProvider, CancellationToken shutdownToken)
   at Foundatio.Hosting.Startup.StartupExtensions.<>c__DisplayClass0_1.<<RunStartupActionsAsync>b__3>d.MoveNext()

**Comment by niemyjski** [comment] 2020-04-03 11:11
I'm not reproducing this, how did you all upgrade? You need to have two separate Elasticsearch services running and run the migration job as per the migration doc (https://github.com/exceptionless/Exceptionless/wiki/Upgrading). If you just upgraded the image in the docker-compose on your existing install that potentially corrupted the data and is probably this error. I think this is the error you are running into because include_in_all isn't in the new index formats.

**Comment by gebiWangshushu** [comment] 2020-04-05 04:55
thank you for you commented！I not upgrading ，is clean Installation. I just followed the (https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting) and  run   `docker-compose up` error appeared.

**Comment by niemyjski** [comment] 2020-04-06 13:54
I'm not seeing this on my Mac or Parallels VM, I'm going to install docker on a clean Windows 10 pc and try to see if I can replicate.

**Comment by niemyjski** [comment] 2020-04-07 14:09
I just started up by fresh windows 10 pc, installed docker, git cloned and did `docker-compose up` for the first time and it started right up. Could you try doing `docker-compose up elasticsearch kibana` and then run `curl -XDELETE localhost:9200/*` or open kibana and do `DELETE *` to reset everything (only do this if you have no data you care about) and then do `docker-compose up`. Does this solve it?

**Comment by gebiWangshushu** [comment] 2020-04-11 09:00
Sorry for not responding in time, I am leaning, I think I will find the way solved it. thank you again for your work!

**Comment by niemyjski** [comment] 2020-04-20 12:43
I'm going to close this as it seems resolved. I'm not sure what was going on as I haven't been able to reproduce and debug it.

**Closed by niemyjski** 2020-04-20 12:43 UTC
