### ISSUE TITLE
Why will it go back

### ISSUE THREAD

**Issue by ysq5202121** [exceptionless/Exceptionless#1163] opened 2022-09-14 06:48 UTC
![企业微信截图_20220914144632](https://user-images.githubusercontent.com/8586973/190080685-6c1f3023-2763-4742-a2aa-0583a83e7443.png)
![企业微信截图_20220914144642](https://user-images.githubusercontent.com/8586973/190080755-780f9b62-5476-41fe-9f90-ed4dc799db9c.png)
After the data is written in, the data is restored in a few seconds

**Comment by ysq5202121** [comment] 2022-09-14 06:59
![image](https://user-images.githubusercontent.com/8586973/190083233-1009e98d-322e-4ca8-ae6d-df6ff18fd2f7.png)
Revocation will occur after submission

**Comment by ysq5202121** [comment] 2022-09-14 09:47
![image](https://user-images.githubusercontent.com/8586973/190121430-bb0e35e4-af8b-4016-9638-0f4453799a12.png)
It was written to the database and then suddenly disappeared

**Comment by niemyjski** [comment] 2022-09-14 12:01
I'm really not sure what you are asking or what issue you are seeing. If you are referring to the counts, make sure project settings has the setting for deleting bot data turned off. It would also help looking through the app logs

**Comment by ysq5202121** [comment] 2022-09-16 01:55
> I'm really not sure what you are asking or what issue you are seeing. If you are referring to the counts, make sure project settings has the setting for deleting bot data turned off. It would also help looking through the app logs.
> 
> Can you provide us with the code snippet above as well as exactly what to do to reproduce in a new project.


The original count is 450. After I trigger the log submission, the count becomes 459. The log record information appears on the following list page. After about 1 minute, the count will be restored to 450. At the same time, the list log will also be deleted, regardless of how many attempts are made. (The database is increased, but the newly added log will be deleted.)

**Comment by niemyjski** [comment] 2022-09-16 11:06
Is the project settings for deleting bot data turned off?

**Comment by ysq5202121** [comment] 2022-09-19 08:18
Not open

**Comment by ysq5202121** [comment] 2022-09-29 06:54
It's troublesome

**Comment by ysq5202121** [comment] 2022-09-29 07:23
If you deploy new applications through Docker, do you want to use dockefile or Docker-compose.yml

**Comment by ysq5202121** [comment] 2022-09-29 07:24
I'm using iis now

**Comment by niemyjski** [comment] 2022-09-29 12:55
I just want the steps needed to reproduce in a new clean environment.

1. clone repo
2. docker compose up
3. create 1 project
4. submit this exact payload(s) in this order
5. verify you see xyz in the ui
6. submit this exact payload
7. you should see xyz.

**Comment by ysq5202121** [comment] 2022-10-24 08:45
![企业微信截图_20221024163315](https://user-images.githubusercontent.com/8586973/197485784-7ca71b16-d223-4b66-9112-677a0e16928e.png)
Occasional erro

**Comment by niemyjski** [comment] 2022-10-24 14:32
Hello,

I'm closing this due to events are being removed due to bot settings. You can turn off remove bot data in project settings.

I'm not sure why your update stacks are failing with version conflicts. I'd open a new issue with detailed steps to reproduce (as stated here https://github.com/exceptionless/Exceptionless/issues/1163#issuecomment-1262238396)

**Closed by niemyjski** 2022-10-24 14:32 UTC
