### ISSUE TITLE
docke-compose up,/api/v2/push not found.

### ISSUE THREAD

**Issue by zhangjiaxianger** [exceptionless/Exceptionless#1009] opened 2021-11-27 15:06 UTC
1.我参考https://github.com/exceptionless/Exceptionless/blob/master/samples/docker-compose.yml,注释了https相关配置,运行成功之后,在app容器中看到如下信息,第一个是es unhealthy，第二个是api not found,请问是哪里的问题,是否会导致数据丢失,我该如何处理?  
2.我是想在生产环境中只使用在docker部署,不使用k8s,使用exceptionless/app、exceptionless/job:latest两个image,redis和es采用azure service,这种环境下,也会出现api not found的问题.
谢谢.
![image](https://user-images.githubusercontent.com/34804813/143686417-d0dc6eaf-e31a-42da-9f5e-e8a68ccd8a58.png)

我的docker-compose.yml文件:
```
version: '3.7'

services:
  app:
    depends_on:
      - elasticsearch
      - redis
    image: exceptionless/app:latest
    environment:
      EX_AppMode: Production
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
      #ASPNETCORE_URLS: http://+;https://+
      #ASPNETCORE_HTTPS_PORT: 5001
      #ASPNETCORE_Kestrel__Certificates__Default__Password: password
      #ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      EX_RunJobsInProcess: 'false'
    ports:
      - 5000:80
      - 5001:443
    volumes:
      - ex_appdata:/app/storage
      - ex_ssldata:/https

  jobs:
    depends_on:
      - app
    image: exceptionless/job:latest
    environment:
      EX_AppMode: Production
      EX_BaseURL: http://localhost:5100
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
    volumes:
      - ex_appdata:/app/storage

  elasticsearch:
    image: exceptionless/elasticsearch:7.15.2
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ex_esdata:/usr/share/elasticsearch/data

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.15.2
    ports:
      - 5601:5601

  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379

volumes:
  ex_esdata:
    driver: local
  ex_appdata:
    driver: local
  ex_ssldata:
    driver: local
```

**Comment by niemyjski** [comment] 2021-11-29 14:32
Hello,

What do you see when you do `docker ps`? Is Elasticsearch running? Can you share the elastic docker logs? Also, if you could please google translate any future feedback that would be a huge help.

**Comment by zhangjiaxianger** [comment] 2021-11-30 05:02
oh, thanks,

I checked the log and found that ES does have an exception. I tried to change several images, but none of them were solved. I will not look at the problem of ES for the time being, and I will use ES and Redis of azure service and come back to the ES problem.
This is my new yml file,  the message  can be  written to exceptionless service, but there are some 'API not found', which I don't know why.

#### docker-compose.yml
version: '3.7'
```
services:
  app:
    image: exceptionless/app:latest
    environment:
      EX_AppMode: Production
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=my_conn_str
      EX_ConnectionStrings__MessageBus: provider=redis
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=my_conn_str
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
      ASPNETCORE_URLS: http://+;
      EX_RunJobsInProcess: 'false'
    ports:
      - 5000:80
    volumes:
      - ex_appdata:/app/storage
      - ex_ssldata:/https

  jobs:
    depends_on:
      - app
    image: exceptionless/job:latest
    environment:
      EX_AppMode: Production
      EX_BaseURL: http://localhost:5100
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=my_conn_str
      EX_ConnectionStrings__MessageBus: provider=redis
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=my_conn_str
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
    volumes:
      - ex_appdata:/app/storage

volumes:
  ex_appdata:
    driver: local
  ex_ssldata:
    driver: local
```
#### docker ps
```
[root@KTJL2 ~]# docker  ps
CONTAINER ID   IMAGE                      COMMAND                  CREATED             STATUS             PORTS                                   NAMES
9c82bbf8314d   exceptionless/job:latest   "dotnet Exceptionles…"   About an hour ago   Up About an hour                                           exceptionless-710_jobs_1
37ded282f4af   exceptionless/app:latest   "/app/app-docker-ent…"   About an hour ago   Up About an hour   0.0.0.0:5000->80/tcp, :::5000->80/tcp   exceptionless-710_app_1

```
#### logs of app 
```
/app/wwwroot /app
Exceptionless UI Config
    .constant('BASE_URL', '' || window.location.origin)
    .constant('EXCEPTIONLESS_API_KEY', '')
    .constant('EXCEPTIONLESS_SERVER_URL', '')
    .constant('FACEBOOK_APPID', '')
    .constant('GITHUB_APPID', '')
    .constant('GOOGLE_APPID', '')
    .constant('INTERCOM_APPID', '')
    .constant('LIVE_APPID', '')
    .constant('SLACK_APPID', '')
    .constant('STRIPE_PUBLISHABLE_KEY', '')
    .constant('SYSTEM_NOTIFICATION_MESSAGE', '')
    .constant('USE_HTML5_MODE', true)
    .constant('USE_SSL', false)
    .constant('ENABLE_ACCOUNT_CREATION', true);
/app
[03:37:40 WRN] Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
[03:37:40 WRN] No XML encryptor configured. Key {da177e21-baef-4e2d-a33b-7f42221ba5e0} may be persisted to storage in unencrypted form.
[03:37:40 WRN] Metrics reporting is NOT enabled on 37ded282f4af.
[03:37:40 WRN] Emails will NOT be sent until the SmtpHost is configured on 37ded282f4af
[03:37:40 INF] Now listening on: http://[::]:80
[03:37:40 INF] Application started. Press Ctrl+C to shut down.
[03:37:40 INF] Hosting environment: Production
[03:37:40 INF] Content root path: /app
[03:37:41 ERR] traceID=ff3d4668a2c8c7c9d15f2352b93ed3a7 HTTP GET /api/v2/push?access_token=sDglPrQ0aiGQgm3SpAbKEZwH5d3kfLIx7QFifr28 responded 503 in 6.4743 ms
[03:37:44 WRN] Token sDglPrQ0aiGQgm3SpAbKEZwH5d3kfLIx7QFifr28 for /api/v2/push not found.
[03:37:48 WRN] Token sDglPrQ0aiGQgm3SpAbKEZwH5d3kfLIx7QFifr28 for /api/v2/push not found.
[03:37:52 WRN] Token sDglPrQ0aiGQgm3SpAbKEZwH5d3kfLIx7QFifr28 for /api/v2/push not found.
[03:37:55 WRN] Token sDglPrQ0aiGQgm3SpAbKEZwH5d3kfLIx7QFifr28 for /api/v2/push not found.
[03:37:59 WRN] Token sDglPrQ0aiGQgm3SpAbKEZwH5d3kfLIx7QFifr28 for /api/v2/push not found.
[03:38:03 WRN] Token sDglPrQ0aiGQgm3SpAbKEZwH5d3kfLIx7QFifr28 for /api/v2/push not found.
[03:38:09 WRN] Token sDglPrQ0aiGQgm3SpAbKEZwH5d3kfLIx7QFifr28 for /api/v2/push not found.
[03:38:11 WRN] Token sDglPrQ0aiGQgm3SpAbKEZwH5d3kfLIx7QFifr28 for /api/v2/push not found.
[03:38:14 WRN] Token sDglPrQ0aiGQgm3SpAbKEZwH5d3kfLIx7QFifr28 for /api/v2/organizations not found.
[03:38:14 WRN] Token sDglPrQ0aiGQgm3SpAbKEZwH5d3kfLIx7QFifr28 for /api/v2/events/61a5983315e5f80001416eea not found.
[03:38:14 WRN] Token sDglPrQ0aiGQgm3SpAbKEZwH5d3kfLIx7QFifr28 for /api/v2/users/me not found.
[03:38:14 WRN] Token sDglPrQ0aiGQgm3SpAbKEZwH5d3kfLIx7QFifr28 for /api/v2/auth/logout not found.
[03:38:17 WRN] Token sDglPrQ0aiGQgm3SpAbKEZwH5d3kfLIx7QFifr28 for /api/v2/push not found.
[03:38:55 WRN] Token vnPRJfFtUbS00WZzzsMxyUUrngC3Iwuk09UQaBia for /api/v2/events not found.
[03:46:25 WRN] Token vnPRJfFtUbS00WZzzsMxyUUrngC3Iwuk09UQaBia for /api/v2/events not found.
```
#### logs of job
```
[03:37:40 WRN] Metrics reporting is NOT enabled on 9c82bbf8314d.
[03:37:40 WRN] Emails will NOT be sent until the SmtpHost is configured on 9c82bbf8314d
[03:37:40 WRN] Index Configuration is NOT enabled on 9c82bbf8314d
[03:37:41 INF] Queue prod-WorkItemDataa14a8d85a203adf0c41192 created. Retries: 2 Retry Delay: 0:01:00, Maintenance Interval: 0:01:00
[03:37:41 INF] All new indexes will be created with 1 Shards and 1 Replicas
[03:37:41 INF] Starting job type Exceptionless.Core.Jobs.CleanupDataJob on machine 9c82bbf8314d...
[03:37:41 INF] Starting job type Exceptionless.Core.Jobs.CleanupOrphanedDataJob on machine 9c82bbf8314d...
[03:37:41 INF] Starting job type Exceptionless.Core.Jobs.Elastic.MaintainIndexesJob on machine 9c82bbf8314d...
[03:37:41 INF] Starting index maintenance...
[03:37:41 INF] Got lock to maintain indexes
[03:37:42 INF] Retrieved list of 2 indexes in 0:00:00.5523169
[03:37:42 INF] Finished index maintenance in 0:00:00.8171295.
[03:37:42 INF] Cleaning up 0 soft deleted organization(s)
[03:37:42 INF] Cleaning up 0 soft deleted project(s)
[03:37:42 INF] maintainindexes job completed
[03:37:42 INF] Cleaning up 0 soft deleted stack(s)
[03:37:42 INF] Starting job type Exceptionless.Core.Jobs.CloseInactiveSessionsJob on machine 9c82bbf8314d...
[03:37:42 INF] Starting job type Exceptionless.Core.Jobs.DownloadGeoIPDatabaseJob on machine 9c82bbf8314d...
[03:37:42 INF] Queue prod-EventPost2b4e4185761421616c84ea created. Retries: 1 Retry Delay: 0:01:00, Maintenance Interval: 0:01:00
[03:37:42 INF] Queue prod-EventNotificationfa48e99bf4116245fe4ac9 created. Retries: 2 Retry Delay: 0:01:00, Maintenance Interval: 0:01:00
[03:37:42 INF] Queue prod-MailMessage3f42049efa2a834be57a10 created. Retries: 2 Retry Delay: 0:01:00, Maintenance Interval: 0:01:00
[03:37:42 INF] Queue prod-WebHookNotificationfc43ad947e764bdbfa682e created. Retries: 2 Retry Delay: 0:01:00, Maintenance Interval: 0:01:00
[03:37:42 INF] Starting job type Exceptionless.Core.Jobs.Elastic.MigrationJob on machine 9c82bbf8314d...
[03:37:42 INF] Queue prod-EventUserDescription8f4a3098fc6d823d2cf06e created. Retries: 2 Retry Delay: 0:01:00, Maintenance Interval: 0:01:00
[03:37:42 INF] Starting job type Exceptionless.Core.Jobs.EventUserDescriptionsJob on machine 9c82bbf8314d...
[03:37:42 INF] Starting job type Exceptionless.Core.Jobs.MailMessageJob on machine 9c82bbf8314d...
[03:37:42 INF] Starting job type Exceptionless.Core.Jobs.StackStatusJob on machine 9c82bbf8314d...
[03:37:42 INF] Starting job type Exceptionless.Core.Jobs.StackEventCountJob on machine 9c82bbf8314d...
[03:37:42 INF] Starting job type Foundatio.Jobs.WorkItemJob on machine 9c82bbf8314d...
[03:37:42 INF] Starting continuous job type WorkItemJob on machine 9c82bbf8314d...
[03:37:42 INF] downloadgeoipdatabase job completed
[03:37:43 INF] Starting job type Exceptionless.Core.Jobs.WebHooksJob on machine 9c82bbf8314d...
[03:37:43 INF] Starting job type Exceptionless.Core.Jobs.DailySummaryJob on machine 9c82bbf8314d...
[03:37:43 INF] Starting job type Exceptionless.Core.Jobs.EventNotificationsJob on machine 9c82bbf8314d...
[03:37:43 INF] Retrieved list of 2 indexes in 0:00:00.8444135
[03:37:43 INF] 0/1: Did not find any missing stacks out of 3
[03:37:43 INF] Found 0 orphaned events from missing stacks out of 3
[03:37:43 INF] Enforcing stack retention period older than 04/04/2021 00:00 for organization kaynetics (61a0a78a5e82500017045e5c), Found 0 Stacks
[03:37:43 INF] Enforced stack retention period for kaynetics (61a0a78a5e82500017045e5c), Removed 0 Stacks
[03:37:43 INF] Enforcing event retention period older than 06/03/2021 00:00 for organization kaynetics (61a0a78a5e82500017045e5c).
[03:37:43 INF] Starting job type Exceptionless.Core.Jobs.EventPostsJob on machine 9c82bbf8314d...
[03:37:43 INF] Enforced event retention period for kaynetics (61a0a78a5e82500017045e5c), Removed 0 Events
[03:37:43 INF] 0/1: Did not find any missing projects out of 1
[03:37:43 INF] Found 0 orphaned events from missing projects out of 1
[03:37:43 INF] Retrieved list of 2 indexes in 0:00:00.0335008
[03:37:43 INF] migration job completed
[03:37:43 INF] 0/1: Did not find any missing organizations out of 1
[03:37:43 INF] Found 0 orphaned events from missing organizations out of 1
[03:37:43 INF] Getting duplicate stacks
[03:37:43 INF] cleanuporphaneddata job completed
[03:37:44 INF] Starting continuous job type StackEventCountJob on machine 9c82bbf8314d...
[03:37:45 INF] Starting continuous job type EventUserDescriptionsJob on machine 9c82bbf8314d...
[03:37:45 INF] Starting continuous job type EventPostsJob on machine 9c82bbf8314d...
[03:37:46 INF] Finished cleaning up data
[03:37:46 INF] cleanupdata job completed
[03:37:47 INF] Starting continuous job type MailMessageJob on machine 9c82bbf8314d...
[03:37:48 INF] Starting continuous job type WebHooksJob on machine 9c82bbf8314d...
[03:37:48 INF] Starting continuous job type EventNotificationsJob on machine 9c82bbf8314d...
[03:37:52 INF] Starting continuous job type StackStatusJob on machine 9c82bbf8314d...
[03:38:12 INF] Starting continuous job type CloseInactiveSessionsJob on machine 9c82bbf8314d...
[03:38:43 INF] Starting continuous job type DailySummaryJob on machine 9c82bbf8314d...
[03:39:19 INF] Processing queue entry: id=9f730b10847f431e9aa83fd844019b14 type=EventPost attempt=1
[03:39:19 INF] Processing post: id=9f730b10847f431e9aa83fd844019b14 path=q/c6c/c6c25e7fc2c34ba98d50ee0e19ba4a2e.payload project=61a0a78a5e82500017045e5d ip=::ffff:58.246.83.10 v=2 agent=exceptionless/4.6.2.0
```

**Comment by niemyjski** [comment] 2021-11-30 12:44
The job is connected to Elastic and from the logs it kind of looks like it only resolved two indexes `Retrieved list of 2 indexes in 0:00:00.5523169` From the app logs it looks it it's not finding any of your api keys and thus why you are getting the 401's. Is that token in elasticsearch under the tokens index (you can check this in kibana)? You could also try creating a new user account and see if this has the same problem. I'd recommend hitting the api's `/health` endpoint too to see if that returns healthy.

**Comment by zhangjiaxianger** [comment] 2021-11-30 14:56
I try to create new accounts and hit  the api's /health endpoint ,I'm downloading the code. Take a look at the code.
Is it not V2 in the code?Or did I see the wrong place?
![image](https://user-images.githubusercontent.com/34804813/144069539-61a25c36-7d03-4486-9d93-9e85c5ce56ce.png)
![image](https://user-images.githubusercontent.com/34804813/144069595-b8a466bc-0a29-4272-b3e4-44d96644f107.png)
![image](https://user-images.githubusercontent.com/34804813/144070444-e0c720d2-3fe2-4ee2-b364-2c3a7a1845bb.png)

**Comment by niemyjski** [comment] 2021-12-01 13:27
It is the default version for all controllers.

**Comment by zhangjiaxianger** [comment] 2021-12-01 13:40
How do I continue to look for this problem, thank you

**Comment by niemyjski** [comment] 2021-12-01 14:07
Did you confirm the following:

>  Is that token in Elasticsearch under the tokens index (you can check this in kibana)? How many indices are listed?

**Comment by niemyjski** [comment] 2021-12-01 14:30
Also if you could share the elastic logs that would help

**Comment by zhangjiaxianger** [comment] 2021-12-01 14:34
I am trying to find relevant information in kibana, I am not familiar with it, it is the first time to use it, I look for it.

**Comment by niemyjski** [comment] 2021-12-01 14:39
Your elasticsearch logs would be in docker and in kibana you'd want to get the documents / cat indices (https://www.elastic.co/guide/en/elasticsearch/reference/7.16/cat-indices.html) from the dev tools.

**Comment by zhangjiaxianger** [comment] 2021-12-01 16:28
is this？
![image](https://user-images.githubusercontent.com/34804813/144273387-ba8a6fa5-5022-47b9-a1ec-f6dd03876c0d.png)

**Comment by niemyjski** [comment] 2021-12-02 02:51
Yes

**Comment by zhangjiaxianger** [comment] 2021-12-02 03:35
Only this in token index,
Data can be written normally, and no problems caused by 'Not Found' have been found so far.
![image](https://user-images.githubusercontent.com/34804813/144352869-a0b936ff-763d-415e-a4b9-75f27a57c98b.png)
![image](https://user-images.githubusercontent.com/34804813/144353180-8c288a16-fa18-4eb0-8d07-700455d1cf45.png)

**Comment by bin97624** [comment] 2021-12-19 17:59
I have this problam,too

**Comment by bin97624** [comment] 2021-12-19 18:01
DO you have nice problam solving ?

**Comment by zhangjiaxianger** [comment] 2021-12-20 02:12
No, I haven't found a solution.
I tried different versions of image with examples yml,no change.

**Comment by niemyjski** [comment] 2021-12-20 11:56
I'm not sure what is going on here. I have not been able to reproduce locally and without exact steps to reproduce this issue there is little I can do to fix this issue. I'd recommend ensuring your docker runtime is up to date, purge docker image data (will lose any exceptionless data you had) and then use a specific docker version instead of latest (`docker run --rm -it -p 5000:80 exceptionless/exceptionless:7.2.1`). If you can send us the steps needed to reproduce this issue reliably it would be a huge help.

**Comment by zhangjiaxianger** [comment] 2021-12-20 14:23
https://user-images.githubusercontent.com/34804813/146781909-188af4c1-377a-4c9d-929e-fadb226753a6.mp4
[demo-logs.txt](https://github.com/exceptionless/Exceptionless/files/7745912/demo-logs.txt)

**Comment by niemyjski** [comment] 2021-12-20 14:40
I'm not seeing any issues with your logs or instance. That last token not found for logout is due to a double request to log out (which should be fixed in the ui but is very low priority).

**Comment by zhangjiaxianger** [comment] 2021-12-20 14:44
ok,
I'm just worried that there will be errors in the data, if only it won't lead to other problems.
thank u .

**Closed** 2021-12-20 14:54 UTC
