### ISSUE TITLE
Organization invite should automatically add me to the logged in account

### ISSUE THREAD

**Issue by ejsmith** [exceptionless/Exceptionless#78] opened 2015-03-28 22:11 UTC
I am logged in with eric@codesmithtools.com and I got an invite for a different email account. The app should just add me to the org with my logged in account. I can then choose to add the other email address as an external login later if I wanted to.

**Comment by niemyjski** [comment] 2015-04-03 17:19
Currently we log you out when you access the signup or login controller (client side). This is the only way to to currently be added to an organization.

**Scenarios to test**
1. Login with existing account and new invite token and verify that you are added.
2. Create two organizations (A and B) with two different user accounts (A and B). Invite user C to organization A and while user B is logged in. User B should now have access to accounts A and B.

Are these the two scenarios you were trying and were failing? I'm taking a look into both of them.

**Comment by niemyjski** [comment] 2015-04-03 17:32
@ejsmith I kind of feel that we should keep the current behavior and log you out if you click on a signup  link from an email. As you may want to create a new account or use an existing one. This way you get that option.

**Comment by niemyjski** [comment] 2015-04-03 17:48
I was not able to reproduce this issue using the two scenarios above using local login (dev). Where you seeing this only using oauth? I've verified that the value we post to the controller is valid.

**Comment by niemyjski** [comment] 2015-04-03 18:13
I was not able to reproduce using oauth and an invite token. I'm closing this issue as I'm unable to reproduce this issue and we just added a ton of logging to the auth controller which will tell us when issues like this happen.

**Comment by ejsmith** [comment] 2015-04-03 19:04
I'm fine with it making me login with an invite token. As long as it works.

Yes, the issue is only with oauth login. Also, we need to make sure that we are capturing the full details of failed attempts to get the user info from the oauth provider.

**Comment by niemyjski** [comment] 2015-04-03 22:14
I verified oauth login is working locally with the google account. I just added additional logging to get the user info from the oauth provider (github one that we know has had errors). As such I'm closing this.

**Closed by niemyjski** 2015-04-03 22:14 UTC
Labels: bug
