### ISSUE TITLE
HipChat integration

### ISSUE THREAD

**Issue by danmiser** [exceptionless/Exceptionless#81] opened 2015-03-31 15:28 UTC
HipChat provides Integrations for a room where 3rd parties can send information directly to a room. A few other crash reporting tools have integration into HipChat already, like Crashlytics and Exceptional. It would be great to get an Exceptionless plugin in there so that I could get automatic notification in real-time in Hipchat about things that happen from Exceptionless (like new error detected, error marked as resolved, or error reoccurred).

**Comment by niemyjski** [comment] 2015-03-31 20:25
We want to have first class plugins as well. Do you want to be able to configure this on a project or organizational level?

As a work around for now, you can get this functionality today with zapier.

**Comment by danmiser** [comment] 2015-04-03 22:52
Project level works fine for me. I went with Zapier to try this out and I have things set up for other Zapier tasks working well, but the MachineName and Error Stack URL fields are not making it all the way to the HipChat room. Anyone have this working with Exceptionless 3 and Hipchat room integrations?

**Comment by niemyjski** [comment] 2015-04-04 00:04
I'll take a look into why they are not showing up

**Comment by niemyjski** [comment] 2015-04-07 18:48
I figured out why zapier integrations are missing that info. It's because all new webhooks created in the ui use v2 and zapier requires v1.

**Comment by niemyjski** [comment] 2015-04-07 19:24
I've found the root cause of the issue. It has to do with serialization. In v2 we moved to a new serialization model which broke some properties on the v1 zapier webhooks. The tests pass because they use an in memory queue which doesn't do serialization but the redis and azure queues use a serializer that changes ErrorStackId to error_stack_id

**Comment by niemyjski** [comment] 2015-04-08 00:58
I just fixed a bug where zapier notifications were off. I made some pretty massive serialization changes that will need a few days to bake before we deploy them.

**Comment by niemyjski** [comment] 2015-04-10 23:44
I've deployed a fix for zapier notifications. Can you please let me know if you are experiencing any issues with your notifications.

**Comment by danmiser** [comment] 2015-04-11 16:15
It’s a bit better. It looks like some partial values started coming through around 4/8. I now get things like “Seq…” as the Message, but the Error Stack URL is still coming in blank. I went back in to Zapier to see if anything looks obviously misconfigured, but it looks fine from what I can see.

**Comment by niemyjski** [comment] 2015-04-12 03:49
Thanks for the heads up, I'll take a look.

**Comment by niemyjski** [comment] 2015-04-16 01:51
I'm not able to reproduce this behavior in my zapier webhooks. Would you mind opening a new issue with the exact steps I need to do to reproduce this on my end (e.g., I setup this zap this way)..

**Comment by danmiser** [comment] 2015-04-18 14:34
Looks like everything is good here.

**Comment by niemyjski** [comment] 2016-01-20 21:55
I'm closing this as it's now merged into 177.

**Closed by niemyjski** 2016-01-20 21:55 UTC
Labels: feature request, help wanted
