### ISSUE TITLE
cdn is a cancer！！！

### ISSUE THREAD

**Issue by 18682788952** [exceptionless/Exceptionless#1105] opened 2022-06-07 09:02 UTC
Many people have responded to this problem. Why is there no detailed solution? A cdn problem has caused the entire site to be unavailable. Isn't this problem worth solving?

**Comment by niemyjski** [comment] 2022-06-07 10:40
We've changed the cdn multiple times, your country keeps blocking valid cdns. We said we'd accept a pr to move this internally.

**Comment by niemyjski** [comment] 2022-06-07 10:42
We'd love if this worked globally but we don't have resources to keep changing cdns. We have stated multiple times we'd accept a pr to bring these into a vender bundle. This is a developer focused tool and it's open source.

**Comment by niemyjski** [comment] 2022-06-07 11:15
Hello,

This is a duplicate of https://github.com/exceptionless/Exceptionless.UI/issues/195. We'd be more than happy to accept a pr for bringing in the dependencies but at this time we can't keep changing the cdn every year when a global acceptable cdn gets banned.

**Closed** 2022-06-07 11:14 UTC
