### ISSUE TITLE
when server get  log : the ES is response error

### ISSUE THREAD

**Issue by a121984376** [exceptionless/Exceptionless#758] opened 2020-10-26 13:22 UTC
[21:16:43 ERR] Error creating the index prod-events-v1-2020.10.26: Original: (400 - ElasticsearchClientException) Request failed to execute. Call: Status code 400 from: PUT /prod-events-v1-2020.10.26. ServerError: Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""
Server: (400) Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""

Original: [ElasticsearchClientException] Request failed to execute. Call: Status code 400 from: PUT /prod-events-v1-2020.10.26. ServerError: Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""
Server Error (Index=null): Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]
[400] PUT /prod-events-v1-2020.10.26

System.AggregateException: One or more errors occurred. (Request failed to execute. Call: Status code 400 from: PUT /prod-events-v1-2020.10.26. ServerError: Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]"") (Request failed to execute. Call: Status code 400 from: PUT /prod-events-v1-2020.10.26. ServerError: Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]"")
 ---> Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: PUT /prod-events-v1-2020.10.26. ServerError: Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""
   --- End of inner exception stack trace ---
[21:16:43 FTL] Error processing action: SaveEventAction Message: Error creating the index prod-events-v1-2020.10.26: Original: (400 - ElasticsearchClientException) Request failed to execute. Call: Status code 400 from: PUT /prod-events-v1-2020.10.26. ServerError: Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""
Server: (400) Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""
-------------------------------
![C9EE0FF3-D47D-4487-80FD-E935B11326B4](https://user-images.githubusercontent.com/15758574/97177584-59600200-17d1-11eb-81d5-a2e214566277.png)

**Comment by niemyjski** [comment] 2020-10-26 13:28
This is a duplicate of #681, can you please see the discussion for the solution. Please let us know if you have any questions.

**Closed by niemyjski** 2020-10-26 13:28 UTC
