### ISSUE TITLE
This problem has been happening all the time

### ISSUE THREAD

**Issue by ysq5202121** [exceptionless/Exceptionless#965] opened 2021-09-18 03:26 UTC
![image](https://user-images.githubusercontent.com/8586973/133870985-ca639f75-2c95-46d7-bf79-1bbd93b7ccc5.png)

不带任何条件查询，出现该问题
This problem occurs when you query without any criteria

**Comment by niemyjski** [comment] 2021-09-20 11:58
This is a duplicate of #935, Please try out the 7.1.0 release and leave a comment with your findings and also make sure you run the CleanupData job which is really important. Make sure to include useful statics like number of stacks per project, number of projects, etc..

**Comment by ysq5202121** [comment] 2021-09-22 08:41
The problem is different. I don't know the specific reason

**Comment by ysq5202121** [comment] 2021-09-22 08:56
![image](https://user-images.githubusercontent.com/8586973/134313823-a7da0fd9-b503-4b37-ba4f-2eaa1d018df9.png)

**Comment by niemyjski** [comment] 2021-09-22 10:35
I'd check your Elasticsearch cpu and memory limits. It kind of looks like it's out of resources as it's circuit breaking. You may need to increase the RAM and CPU for the instance.

**Comment by ysq5202121** [comment] 2021-09-25 03:09
[storage] What does this folder do? It's very large and takes up hundreds of GB
![image](https://user-images.githubusercontent.com/8586973/134755923-500d892f-92d5-4000-9a95-0eb6b30cbdf1.png)

**Comment by niemyjski** [comment] 2021-09-27 11:43
You probably want to set `EX_EnableArchive` to false. This will be the new default in the next release so events don't get saved to storage. You can remove this folder to free up space as each event comes into the system, it's saved to disk.

**Comment by niemyjski** [comment] 2022-01-25 14:47
I'm closing this as you'd want to turn off the archive which is the new default.

**Closed by niemyjski** 2022-01-25 14:47 UTC
