### ISSUE TITLE
Can't create project

### ISSUE THREAD

**Issue by Nonobis** [exceptionless/Exceptionless#740] opened 2020-10-11 10:59 UTC
Hello,

On last docker version, i can't create project, i have got an exception.

[12:55:26 ERR] Unhandled error: Could not convert string to DateTimeOffset: 0001-01-01T00:00:00. Path 'last_event_date_utc', line 1, position 566.
Elasticsearch.Net.UnexpectedElasticsearchClientException: Could not convert string to DateTimeOffset: 0001-01-01T00:00:00. Path 'last_event_date_utc', line 1, position 566.
---> Newtonsoft.Json.JsonReaderException: Could not convert string to DateTimeOffset: 0001-01-01T00:00:00. Path 'last_event_date_utc', line 1, position 566.
at Newtonsoft.Json.JsonReader.ReadDateTimeOffsetString(String s)
at Newtonsoft.Json.JsonReader.ReadAsDateTimeOffset()
at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
at Exceptionless.Serializer.DataObjectConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /app/src/Exceptionless.Core/Serialization/DataObjectConverter.cs:line 64
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
at Nest.JsonNetSerializer.ConnectionSettingsAwareSerializerBase.Deserialize[T](Stream stream)
at Elasticsearch.Net.DiagnosticsSerializerProxy.Deserialize[T](Stream stream)
at Nest.SourceFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
at Elasticsearch.Net.Utf8Json.JsonSerializer.DeserializeAsync[T](Stream stream, IJsonFormatterResolver resolver)
at Elasticsearch.Net.ResponseBuilder.SetBodyAsync[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType, CancellationToken cancellationToken)
at Elasticsearch.Net.ResponseBuilder.ToResponseAsync[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType, CancellationToken cancellationToken)
at Elasticsearch.Net.HttpConnection.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
at Elasticsearch.Net.RequestPipeline.CallElasticsearchAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
--- End of inner exception stack trace ---
at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
at Foundatio.Repositories.Elasticsearch.ElasticReadOnlyRepositoryBase`1.GetByIdAsync(Id id, ICommandOptions options)
at Exceptionless.Core.Billing.BillingManager.CanAddProjectAsync(Project project) in /app/src/Exceptionless.Core/Billing/BillingManager.cs:line 44
at Exceptionless.Web.Controllers.ProjectController.CanAddAsync(Project value) in /app/src/Exceptionless.Web/Controllers/ProjectController.cs:line 682
at Exceptionless.Web.Controllers.RepositoryApiController`5.PostImplAsync(TNewModel value) in /app/src/Exceptionless.Web/Controllers/Base/RepositoryApiController.cs:line 33
at lambda_method460(Closure , Object )
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

**Comment by niemyjski** [comment] 2020-10-12 14:15
This looks like a duplicate of #722 Can you please take a look at that issue and see if you possibly have the `- /etc/localtime:/etc/localtime:ro` volume defined as well. Or what we'd need to reproduce.

**Closed by niemyjski** 2020-10-12 14:15 UTC

**Comment by niemyjski** [comment] 2020-10-18 19:20
v7.0.4 has now been released https://github.com/exceptionless/Exceptionless/releases/tag/v7.0.4
