### ISSUE TITLE
Events are in random order if they have the same timestamp

### ISSUE THREAD

**Issue by KasperLK** [exceptionless/Exceptionless#86] opened 2015-04-08 22:07 UTC

**Comment by niemyjski** [comment] 2015-04-09 01:22
Can you please expand on this subject as I'm not completely following. Are you referring to the ui?

**Comment by KasperLK** [comment] 2015-04-09 05:39
Yes in the UI.
After some more testing, it looks like it's random.
If i submit two events right after each other, the order in the UI is not always the same they were submitted in.
If i do a sleep of 1 ms between the two submit, the order is correct.

**Comment by niemyjski** [comment] 2015-04-09 18:54
This could because they are submitted with the same exact date time. When it's created with the same exact date time it will show up in the order they were returned as from elastic search. Can you please confirm this by looking at the [date on the two created events](https://api.exceptionless.io/docs/index#!/Event/Event_GetById). What is it set to? Are they the same time?

**Comment by KasperLK** [comment] 2015-04-09 19:07
I think they are the same. I can't see milliseconds, but if i insert a sleep for 1 millisesond then the order is correct.

**Comment by KasperLK** [comment] 2015-04-09 19:09
Ahh. I didn't see the api link. I will try that and get back to you.

**Comment by niemyjski** [comment] 2015-04-09 19:11
You can get your api key by logging in [here](https://api.exceptionless.io/docs/index#!/Auth/Auth_Login).

**Comment by KasperLK** [comment] 2015-04-09 19:49
The datetimes are exactly the same.

**Comment by niemyjski** [comment] 2015-04-09 19:52
When we get the events back from elasticsearch we tell it to sort by date and nothing else for most views so it should be in the order it's received (but it's not guaranteed). I'm not sure what should happen here as it's by design.

@ejsmith thoughts?

**Comment by KasperLK** [comment] 2015-04-09 20:32
Hmm... Not without some sequential id.

**Comment by niemyjski** [comment] 2015-04-09 20:34
It's created with a semi sequential id but it's created in the order
they are added.Are the id's close?

On 4/9/15, Kasper Kirkegaard <notifications@github.com> wrote:
> Hmm... Not without some sequential id.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/exceptionless/Exceptionless/issues/86#issuecomment-91348600


-- 
Thanks
-Blake Niemyjski

**Comment by niemyjski** [comment] 2015-04-29 15:03
Do you have the id's that created it, I'm curious if they are sequential. Is there any chance you could put a unit test together that reproduces this and we could take a closer look. I would think that the events would be processed in the order they are sent in. If they are sent in via bulk, I'd think we'd process them in the order they exist in the json array.

**Comment by niemyjski** [comment] 2015-07-20 20:34
@KasperLK any chance you could please take a look at my previous response.

**Comment by niemyjski** [comment] 2016-01-12 18:30
I'm closing this as we will process events based on the order they are received as well as there timestamp.

**Closed by niemyjski** 2016-01-12 18:30 UTC
Labels: question
